### ISSUE TITLE
SPH and Octree AMR Datasets Failing in volume rendering, OAProj, Interactive Data Viz

### ISSUE THREAD

**Issue by yt-fido** [yt-project/yt#1212]
Originally reported by: **chummels (Bitbucket: [chummels](https://bitbucket.org/chummels), GitHub: [chummels](https://github.com/chummels))**

----------------------------------------

This similar to Issues #788, #986, #1008, #1183, but I think this description generalizes and distills all of these problems.

It appears that all particle-based (or Octree-based) datasets are segfaulting when one attempts to do anything involving the KDTree with them.  The following three scripts all fail with the same result:

```
#!python

import yt
ds = yt.load("gizmo_cosmology_plus/snap_N128L16_151.hdf5")
L = ds.arr([1,0,0], 'unitary')
yt.OffAxisProjectionPlot(ds, L, 'density').save()
```

```
#!python

import yt
ds = yt.load("gizmo_cosmology_plus/snap_N128L16_151.hdf5")
im, sc = yt.volume_render(ds, 'density', fname='rendering.png')

```

```
#!python

import yt
ds = yt.load("gizmo_cosmology_plus/snap_N128L16_151.hdf5")
yt.interactive_render(ds)
```

These all fail with some variation on this output:

```
#!python

Failed to split grids.
Failed to split grids.
Segmentation fault
```

The above scripts each use the publicly available dataset `gizmo_cosmology_plus`, but one gets similar results by using the same simple commands on any of the SPH datasets on http://yt-project.org/data/ e.g. `TipsyGalaxy`, `snapshot_033`, `GadgetDiskGalaxy`.

Notably, however, when you run the same script with Octree-based AMR outputs, you get similar results.  Example datasets that do this are Ramses (e.g. `output_00080`), and ART (e.g. `D9p_500`).

These scripts were run on an OS X installation with the tip of yt-dev (843a342ee510).

----------------------------------------
- Bitbucket: https://bitbucket.org/yt_analysis/yt/issue/1212

**Comment by ngoldbaum** [comment]
At least for SPH data, I would like to write a new particle-focused ray tracing engine. Optimally we would engineer things so it's a drop-in replacement for the grid VR engine and AMRKDTree. That should ease support for oct data if anyone wants to write an oct VR engine.

**Comment by chummels** [comment]
Update on this for 2019.  Of the scripts that I provided in the original issue, the first one is now resolved, but the second one still fails:

```
import yt
ds = yt.load("gizmo_cosmology_plus/snap_N128L16_151.hdf5")
im, sc = yt.volume_render(ds, ('gas', 'density'), fname='rendering.png')
```

However, the traceback yields:

```
Traceback (most recent call last):
  File "test1.py", line 5, in <module>
    im, sc = yt.volume_render(ds, 'density', fname='rendering.png')
  File "/Users/chummels/src/yt-conda/src/yt-git/yt/visualization/volume_rendering/volume_rendering.py", line 136, in volume_render
    im = sc.render()
  File "/Users/chummels/src/yt-conda/src/yt-git/yt/visualization/volume_rendering/scene.py", line 229, in render
    bmp = self.composite(camera=camera)
  File "/Users/chummels/src/yt-conda/src/yt-git/yt/visualization/volume_rendering/scene.py", line 545, in composite
    im = source.render(camera, zbuffer=opaque)
  File "/Users/chummels/src/yt-conda/src/yt-git/yt/visualization/volume_rendering/render_source.py", line 74, in wrapper
    obj.volume.set_fields(fields, log_fields,
  File "/Users/chummels/src/yt-conda/src/yt-git/yt/visualization/volume_rendering/render_source.py", line 231, in volume
    volume = AMRKDTree(self.data_source.ds, data_source=self.data_source)
  File "/Users/chummels/src/yt-conda/src/yt-git/yt/utilities/amr_kdtree/amr_kdtree.py", line 157, in __init__
    raise RuntimeError("AMRKDTree does not support particle or octree-based data.")
RuntimeError: AMRKDTree does not support particle or octree-based data.
```

I recall that there is now a way to do volume rendering in yt4, I just don't remember how.  Maybe to finally resolve this issue, we only now need to tie the default `volume_render()` or `create_scene()` functionality into the alternate method?  I wasn't able to test the interactive volume renderer if it worked with particle-based datasets, because I was unable to `pip install cyglfw3`, one of its dependencies.

**Comment by MatthewTurk** [comment]
@chummels Thanks for digging this up!  I think that with #2166 we might be able to move this to closed, but for now, only AMR works still with volume rendering.

**Comment by ngoldbaum** [comment]
I was hoping to have a student write an SPH volume renderer last summer. While they did implement off-axis projections, they never got to the point of writing a full-fledged volume renderer. In order to close this issue someone would need to do that. I have ideas for how that would work (e.g. this markdown document I wrote for the student I was working with: https://github.com/ngoldbaum/spin-projects-2018/blob/master/sph-vr/notes.md) but nothing concrete.

We definitely shouldn't block releasing yt 4.0 on getting this working.

**Comment by chummels** [comment]
OK, fair enough.

**Comment by cphyc** [comment]
After #2610 is merged, volume rendering should work with octree (such as RAMSES).

**Comment by Joshuaalbert** [comment]
@cphyc I'm still getting a volume render failure, although now after installing the latest yt from master which has #2610 it's no longer `RuntimeError: AMRKDTree does not support particle or octree-based data.` the new error is in the attached traceback.
```python
import yt
import glob
if __name__ == "__main__":
    ds = yt.load(glob.glob('./*/snap*')[0])
    print(ds)
    im, sc = yt.volume_render(ds, 'density', fname='rendering.png')
```
[traceback.txt](https://github.com/yt-project/yt/files/5417591/traceback.txt)
