### ISSUE TITLE
test_cylindrical_ray_trace randomly fails on appveyor

### ISSUE THREAD

**Issue by ngoldbaum** [yt-project/yt#1403]
Every once in a while, the appveyor build fails with the following error message:

```
======================================================================
ERROR: yt.utilities.lib.tests.test_alt_ray_tracers.test_cylindrical_ray_trace
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Miniconda3-x64\envs\test\lib\site-packages\nose\case.py", line 197, in runTest
    self.test(*self.arg)
  File "c:\projects\yt-1nc0i\yt\utilities\lib\tests\test_alt_ray_tracers.py", line 65, in test_cylindrical_ray_trace
    t, s, rztheta, inds = cylindrical_ray_trace(p1, p2, left_grid, right_grid)
  File "yt\utilities\lib\alt_ray_tracers.pyx", line 203, in yt.utilities.lib.alt_ray_tracers.cylindrical_ray_trace (yt/utilities/lib/alt_ray_tracers.c:6926)
    tsect, tinds = np.unique(tsect[tmask], return_index=True)
ValueError: Item size of buffer (1 byte) does not match size of 'int64_t' (8 bytes)
----------------------------------------------------------------------

```

**Comment by ngoldbaum** [comment]
Possible hint:

```
In [4]: np.unique([1, 2, 3], return_index=True)[1].dtype
Out[4]: dtype('int64')

In [5]: np.unique([], return_index=True)[1].dtype
Out[5]: dtype('bool')

In [6]: np.__version__
Out[6]: '1.12.1'
```
