### ISSUE TITLE
test_fast_find_field_values_at_points is randomly failing on travis

### ISSUE THREAD

**Issue by ngoldbaum** [yt-project/yt#1823]
I've noticed this failure mode the past few days happening randomly on travis:

```
ERROR: yt.data_objects.tests.test_points.test_fast_find_field_values_at_points
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/yt-project/yt/venv/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/travis/build/yt-project/yt/yt/data_objects/tests/test_points.py", line 60, in test_fast_find_field_values_at_points
    ppos = ppos[np.random.random_integers(0, len(ppos), size=nparticles)]
  File "/home/travis/build/yt-project/yt/yt/units/yt_array.py", line 1036, in __getitem__
    ret = super(YTArray, self).__getitem__(item)
IndexError: index 4096 is out of bounds for axis 0 with size 4096
```

**Comment by git-abhishek** [comment]
Probably `ppos = ppos[np.random.random_integers(0, len(ppos), size=nparticles)]` should be `    ppos = ppos[np.random.random_integers(0, len(ppos)-1, size=nparticles)]`.

**Comment by ngoldbaum** [comment]
yup, agreed :) see #1824.
