### ISSUE TITLE
Particle Filters Fail with Projections

### ISSUE THREAD

**Issue by chummels** [yt-project/yt#1975]
### Bug report

**Bug summary**

With the demeshening, particle filters (breaking up the particles based on some field constraints), fail when you actually try to make ProjectionPlots and presumably other PlotWindow objects.  Docs reference for filtering particle fields: http://yt-project.org/docs/dev/analyzing/filtering.html#filtering-particle-fields

**Code for reproduction**

```python
import yt

def _cool_gas(pfilter, data):
    filter = data[(pfilter.filtered_type, "temperature")] < 1e5
    return filter

yt.add_particle_filter("cool_gas", function=_cool_gas, filtered_type='PartType0',
                    requires=["temperature"])

ds = yt.load('FIRE_M12i_ref11/snapshot_600.hdf5')
ds.add_particle_filter('cool_gas')
yt.ProjectionPlot(ds, 'x', ('cool_gas', 'density')).save()
```

**Actual outcome**

```
python ~/src/yt-data/test_particle_filter.py
/Users/chummels/src/yt-conda/lib/python3.6/site-packages/cmocean/tools.py:76: MatplotlibDeprecationWarning: The is_string_like function was deprecated in version 2.1.
  if not mpl.cbook.is_string_like(rgbin[0]):
yt : [INFO     ] 2018-08-15 15:22:31,960 Calculating time from 1.000e+00 to be 4.355e+17 seconds
yt : [INFO     ] 2018-08-15 15:22:31,961 Assuming length units are in kpc/h (comoving)
yt : [INFO     ] 2018-08-15 15:22:31,983 Parameters: current_time              = 4.3545571088051386e+17 s
yt : [INFO     ] 2018-08-15 15:22:31,983 Parameters: domain_dimensions         = [1 1 1]
yt : [INFO     ] 2018-08-15 15:22:31,983 Parameters: domain_left_edge          = [ 0.  0.  0.]
yt : [INFO     ] 2018-08-15 15:22:31,983 Parameters: domain_right_edge         = [ 60000.  60000.  60000.]
yt : [INFO     ] 2018-08-15 15:22:31,984 Parameters: cosmological_simulation   = 1
yt : [INFO     ] 2018-08-15 15:22:31,984 Parameters: current_redshift          = 0.0
yt : [INFO     ] 2018-08-15 15:22:31,984 Parameters: omega_lambda              = 0.728
yt : [INFO     ] 2018-08-15 15:22:31,984 Parameters: omega_matter              = 0.272
yt : [INFO     ] 2018-08-15 15:22:31,984 Parameters: hubble_constant           = 0.702
yt : [INFO     ] 2018-08-15 15:22:32,177 Allocating for 4.787e+06 particles
Initializing coarse index : 100%|██████████████████████████████████████████████████████| 10/10 [00:00<00:00, 18.65it/s]
Initializing refined index: 100%|██████████████████████████████████████████████████████| 10/10 [00:01<00:00, 16.99it/s]
yt : [INFO     ] 2018-08-15 15:22:35,422 Loading KDTree from snapshot_600.hdf5.kdtree
yt : [INFO     ] 2018-08-15 15:22:35,682 Detected hash mismatch, regenerating KDTree
yt : [INFO     ] 2018-08-15 15:22:35,734 Allocating KDTree for 753678 particles
yt : [INFO     ] 2018-08-15 15:22:36,614 xlim = 0.000000 60000.000000
yt : [INFO     ] 2018-08-15 15:22:36,614 ylim = 0.000000 60000.000000
yt : [INFO     ] 2018-08-15 15:22:36,615 xlim = 0.000000 60000.000000
yt : [INFO     ] 2018-08-15 15:22:36,615 ylim = 0.000000 60000.000000
yt : [INFO     ] 2018-08-15 15:22:36,617 Making a fixed resolution buffer of (('cool_gas', 'density')) 800 by 800
Traceback (most recent call last):
  File "/Users/chummels/src/yt-data/test_particle_filter.py", line 12, in <module>
    yt.ProjectionPlot(ds, 'x', ('cool_gas', 'density')).save()
  File "/Users/chummels/src/yt-conda/src/yt-git/yt/visualization/plot_window.py", line 1483, in __init__
    aspect=aspect)
  File "/Users/chummels/src/yt-conda/src/yt-git/yt/visualization/plot_window.py", line 670, in __init__
    PlotWindow.__init__(self, *args, **kwargs)
  File "/Users/chummels/src/yt-conda/src/yt-git/yt/visualization/plot_window.py", line 229, in __init__
    self._setup_plots()
  File "/Users/chummels/src/yt-conda/src/yt-git/yt/visualization/plot_window.py", line 789, in _setup_plots
    image = self.frb[f]
  File "/Users/chummels/src/yt-conda/src/yt-git/yt/visualization/fixed_resolution.py", line 135, in __getitem__
    int(self.antialias))
  File "/Users/chummels/src/yt-conda/src/yt-git/yt/geometry/coordinates/cartesian_coordinates.py", line 180, in pixelize
    antialias, dimension, periodic)
  File "/Users/chummels/src/yt-conda/src/yt-git/yt/geometry/coordinates/cartesian_coordinates.py", line 413, in _ortho_pixelize
    data_source['px'], data_source['py'],
  File "/Users/chummels/src/yt-conda/src/yt-git/yt/data_objects/data_containers.py", line 254, in __getitem__
    self.ds.arr(self._generate_container_field(f))
  File "/Users/chummels/src/yt-conda/src/yt-git/yt/data_objects/data_containers.py", line 416, in _generate_container_field
    raise NotImplementedError
NotImplementedError
```

**Expected outcome**

To make a projection.

**Comment by MatthewTurk** [comment]
Looks to me like this may be a result of the visualization machinery trying to use the wrong slicing mechanism.  It may be that there's some way that "which fields are particle fields" gets computed but it doesn't realize that a new particle filter field is done in that manner.

**Comment by chummels** [comment]
I just tested this again, and it appears that the problem is now fixed.  Perhaps PR #1999 was responsible for the fix?  Either way, closing now.  It's a miracle!
