### ISSUE TITLE
Random Travis macOS failures

### ISSUE THREAD

**Issue by jzuhone** [yt-project/yt#2000]
Unusual Travis unit test failures are being reported which are apparently random and only occur on macOS:

```pycon
Traceback (most recent call last):

  File "/usr/local/lib/python2.7/site-packages/nose/case.py", line 197, in runTest

    self.test(*self.arg)

  File "/Users/travis/build/yt-project/yt/yt/data_objects/tests/test_profiles.py", line 295, in test_profile_zero_weight

    assert not np.any(np.isnan(profile['gas', 'radial_velocity']))

AssertionError: 
```
https://travis-ci.org/yt-project/yt/builds/422363360

**Comment by ngoldbaum** [comment]
Here's it happening on python3.6: https://travis-ci.org/yt-project/yt/jobs/422595332

Maybe this is an interaction with another test?

**Comment by ngoldbaum** [comment]
I haven't seen this in a while so I'm closing.
