### ISSUE TITLE
Generating a ProjectionPlot from a particle filter based on an SPH particle fails

### ISSUE THREAD

**Issue by ngoldbaum** [yt-project/yt#2069]
**Bug summary**

Creating a particle filter based on an SPH particle works, but the particle type is not properly recognized as an SPH particle type, causing an error when you try to make a plot using the particle filter.

**Code for reproduction**

```python
import yt
import numpy as np
import matplotlib
matplotlib.use("Agg")
from matplotlib import pyplot as plt

ds = yt.load("gizmo_64/output/snap_N64L16_135.hdf5")

galaxy_pos = ds.arr([14874.90526271, 2789.92175182, 6898.11417307], "kpccm")

@yt.particle_filter("central_gas", requires=["Coordinates"], filtered_type="PartType0")
def _filter(pfilter, data):
    coords = np.abs(data[(pfilter.filtered_type, "Coordinates")] - galaxy_pos)
    return (coords[:, 0] < 10) & (coords[:, 1] < 10) & (coords[:, 2] < 10)

ds.add_particle_filter("central_gas")

plot = yt.ProjectionPlot(
    ds,
    axis="z",
    fields=("central_gas", "density"),
    center=galaxy_pos,
    width=[250., 250., 250.],
)
```

**Actual outcome**

```
Traceback (most recent call last):
  File "test.py", line 23, in <module>
    width=[250., 250., 250.],
  File "/Users/goldbaum/Documents/yt-git/yt/visualization/plot_window.py", line 1483, in __init__
    aspect=aspect)
  File "/Users/goldbaum/Documents/yt-git/yt/visualization/plot_window.py", line 670, in __init__
    PlotWindow.__init__(self, *args, **kwargs)
  File "/Users/goldbaum/Documents/yt-git/yt/visualization/plot_window.py", line 229, in __init__
    self._setup_plots()
  File "/Users/goldbaum/Documents/yt-git/yt/visualization/plot_window.py", line 789, in _setup_plots
    image = self.frb[f]
  File "/Users/goldbaum/Documents/yt-git/yt/visualization/fixed_resolution.py", line 135, in __getitem__
    int(self.antialias))
  File "/Users/goldbaum/Documents/yt-git/yt/geometry/coordinates/cartesian_coordinates.py", line 205, in pixelize
    antialias, dimension, periodic)
  File "/Users/goldbaum/Documents/yt-git/yt/geometry/coordinates/cartesian_coordinates.py", line 452, in _ortho_pixelize
    data_source['px'], data_source['py'],
  File "/Users/goldbaum/Documents/yt-git/yt/data_objects/data_containers.py", line 254, in __getitem__
    self.ds.arr(self._generate_container_field(f))
  File "/Users/goldbaum/Documents/yt-git/yt/data_objects/data_containers.py", line 416, in _generate_container_field
    raise NotImplementedError
NotImplementedError
```

**Expected outcome**

a nice plot

**Comment by chummels** [comment]
Closing.  I have tested that this now works.  Was fixed by PR #2070 .
