### ISSUE TITLE
Some tests fail when running on installed package

### ISSUE THREAD

**Issue by olebole** [yt-project/yt#2123]
### Bug report

When I run the tests on the installed (Debian) package, some tests fail due to permission problems.

**Code for reproduction**

```
$ python3 -c "import yt; exit(yt.run_nose())"
[...]
======================================================================
ERROR: yt.frontends.gadget.tests.test_outputs.test_gadget_binary
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/usr/lib/python3/dist-packages/yt/frontends/gadget/tests/test_outputs.py", line 58, in test_gadget_binary
    fmt=fmt
  File "/usr/lib/python3/dist-packages/yt/frontends/gadget/testing.py", line 67, in fake_gadget_binary
    with open(filename, 'wb') as fp:
PermissionError: [Errno 13] Permission denied: 'fake_gadget_binary'

======================================================================
ERROR: yt.visualization.volume_rendering.tests.test_scene.test_annotations
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/usr/lib/python3/dist-packages/yt/visualization/volume_rendering/tests/test_scene.py", line 111, in test_annotations
    sc.save_annotated('test_scene_annotated.png', text_annotate=[[(.1, 1.05), "test_string"]])
  File "/usr/lib/python3/dist-packages/yt/visualization/volume_rendering/scene.py", line 465, in save_annotated
    self._render_figure.savefig(fname, facecolor='black', pad_inches=0)
  File "/usr/lib/python3/dist-packages/matplotlib/figure.py", line 2062, in savefig
    self.canvas.print_figure(fname, **kwargs)
  File "/usr/lib/python3/dist-packages/matplotlib/backend_bases.py", line 2263, in print_figure
    **kwargs)
  File "/usr/lib/python3/dist-packages/matplotlib/backends/backend_agg.py", line 530, in print_png
    with cbook.open_file_cm(filename_or_obj, "wb") as fh:
  File "/usr/lib/python3.7/contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "/usr/lib/python3/dist-packages/matplotlib/cbook/__init__.py", line 626, in open_file_cm
    fh, opened = to_filehandle(path_or_file, mode, True, encoding)
  File "/usr/lib/python3/dist-packages/matplotlib/cbook/__init__.py", line 611, in to_filehandle
    fh = io.open(fname, flag, encoding=encoding)
PermissionError: [Errno 13] Permission denied: 'test_scene_annotated.png'
```

The reason is that the files are going to be written to the working directory, which is changed somewhere in the tests to `/usr/lib/python3/dist-packages/yt` (the installed package directory), which is not writable by an ordinary user.

It would be great to fix this, since in Debian we use CI tests to regularly check whether the package works when its dependencies change.

Cc: @bwkeller (Debian maintainer of the package)

**Comment by ngoldbaum** [comment]
Thanks for the report! The fix for these is probably to change into a directory provided by `mkdtmp` as we do elsewhere.

We should also look into setting up a test runner that runs the unit tests under tox so this use case gets caught in our CI.
