### ISSUE TITLE
YTBoundsDefinitionError when donig CIC projection

### ISSUE THREAD

**Issue by cphyc** [yt-project/yt#2129]
### Bug report

**Bug summary**

I get a `YTBoundsDefinitionError` when doing a CIC projection of a RAMSES dataset. My data source is a sphere.

**Code for reproduction**

The dataset is a large cosmological dataset (

```python
import yt

ds = yt.load('output_00080/info_00080.txt')

# Get a sphere centred on the main halo
hpos = ds.arr([0.5215110772898429, 0.5215110772898429, 0.5215110772898429], 'code_length')
hrvir = ds.quan(0.021153617650270462, 'Mpc')

sp = ds.sphere(hpos, hrvir)

# Plot DM quantities
kwa = dict(data_source=sp, center=hpos, width=hrvir*2)
p = yt.ProjectionPlot(ds, 'x', 'DM_cic', **kwa)
p.set_cmap('DM_cic', 'bone')
p.save()

```

**Actual outcome**

```
yt : [INFO     ] 2019-01-09 18:50:26,601 Adding particle_type: DM
yt : [INFO     ] 2019-01-09 18:50:26,616 Adding particle_type: star
yt : [INFO     ] 2019-01-09 18:50:26,630 Adding particle_type: cloud
yt : [INFO     ] 2019-01-09 18:50:26,644 Adding particle_type: dust
yt : [INFO     ] 2019-01-09 18:50:26,658 Adding particle_type: star_tracer
yt : [INFO     ] 2019-01-09 18:50:26,672 Adding particle_type: cloud_tracer
yt : [INFO     ] 2019-01-09 18:50:26,687 Adding particle_type: dust_tracer
yt : [INFO     ] 2019-01-09 18:50:26,702 Adding particle_type: gas_tracer
Traceback (most recent call last):
  File "/home/cadiou/codes/yt/yt/data_objects/data_containers.py", line 308, in _generate_fluid_field
    finfo.check_available(gen_obj)
  File "/home/cadiou/codes/yt/yt/fields/derived_field.py", line 204, in check_available
    validator(data)
  File "/home/cadiou/codes/yt/yt/fields/derived_field.py", line 470, in __call__
    raise NeedsGridType(self.ghost_zones,self.fields)
yt.fields.field_exceptions.NeedsGridType: (0, None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "analyse.py", line 20, in <module>
    p = yt.ProjectionPlot(ds, 'x', 'DM_cic', **kwa)
  File "HOME/codes/yt/yt/visualization/plot_window.py", line 1591, in __init__
    max_level=max_level)
  File "HOME/codes/yt/yt/data_objects/construction_data_containers.py", line 270, in __init__
    self.get_data(field)
  File "HOME/codes/yt/yt/data_objects/construction_data_containers.py", line 344, in get_data
    self._handle_chunk(chunk, fields, tree)
  File "HOME/codes/yt/yt/data_objects/construction_data_containers.py", line 450, in _handle_chunk
    d = chunk[field] * dl
  File "HOME/codes/yt/yt/data_objects/data_containers.py", line 255, in __getitem__
    self.get_data(f)
  File "HOME/codes/yt/yt/data_objects/data_containers.py", line 1382, in get_data
    self._generate_fields(fields_to_generate)
  File "HOME/codes/yt/yt/data_objects/data_containers.py", line 1402, in _generate_fields
    fd = self._generate_field(field)
  File "HOME/codes/yt/yt/data_objects/data_containers.py", line 292, in _generate_field
    tr = self._generate_fluid_field(field)
  File "HOME//codes/yt/yt/data_objects/data_containers.py", line 310, in _generate_fluid_field
    rv = self._generate_spatial_fluid(field, ngt_exception.ghost_zones)
  File "HOME//codes/yt/yt/data_objects/data_containers.py", line 330, in _generate_spatial_fluid
    ind += o.select(self.selector, self[field], rv, ind)
  File "HOME//codes/yt/yt/data_objects/data_containers.py", line 255, in __getitem__
    self.get_data(f)
  File "HOME//codes/yt/yt/data_objects/data_containers.py", line 1382, in get_data
    self._generate_fields(fields_to_generate)
  File "HOME//codes/yt/yt/data_objects/data_containers.py", line 1402, in _generate_fields
    fd = self._generate_field(field)
  File "HOME//codes/yt/yt/data_objects/data_containers.py", line 292, in _generate_field
    tr = self._generate_fluid_field(field)
  File "HOME//codes/yt/yt/data_objects/data_containers.py", line 312, in _generate_fluid_field
    rv = finfo(gen_obj)
  File "HOME//codes/yt/yt/fields/derived_field.py", line 256, in __call__
    dd = self._function(self, data)
  File "HOME//codes/yt/yt/fields/particle_fields.py", line 149, in particle_cic
    d = data.deposit(pos, [data[ptype, mass_name]], method = "cic")
  File "HOME//codes/yt/yt/data_objects/octree_subset.py", line 184, in deposit
    op.initialize()
  File "yt/geometry/particle_deposit.pyx", line 345, in yt.geometry.particle_deposit.CICDeposit.initialize
yt.utilities.exceptions.YTBoundsDefinitionError: This operation has encountered a bounds error: CIC requires minimum of 2 zones in all spatial dimensions. Specified bounds are '(2, 2, 2, 1)'.
```

**Version Information**

  * Operating System: Linux
  * Python Version: 3.6.7
  * yt version: 3.6dev0
  * Other Libraries (if applicable):

**Comment by ngoldbaum** [comment]
I have a workaround I think, I just want to make sure it's always safe before making a PR:

```diff
diff --git a/yt/geometry/particle_deposit.pyx b/yt/geometry/particle_deposit.pyx
index bb39baf5b..82b416b39 100644
--- a/yt/geometry/particle_deposit.pyx
+++ b/yt/geometry/particle_deposit.pyx
@@ -340,11 +340,11 @@ cdef class CICDeposit(ParticleDepositOperation):
     cdef np.float64_t[:,:,:,:] field
     cdef public object ofield
     def initialize(self):
-        if not all(_ > 1 for _ in self.nvals):
+        if not all(_ > 1 for _ in self.nvals[:-1]):
             from yt.utilities.exceptions import YTBoundsDefinitionError
             raise YTBoundsDefinitionError(
                 "CIC requires minimum of 2 zones in all spatial dimensions.",
-                self.nvals)
+                self.nvals[:-1])
         self.field = append_axes(
             np.zeros(self.nvals, dtype="float64", order='F'), 4)
```

**Comment by cphyc** [comment]
I can confirm this solves my issue.
