### ISSUE TITLE
Getting the particle files with MemoryError abortion

### ISSUE THREAD

**Issue by mahmoodn** [yt-project/yt#2134]
I want to get some millions of the darksky particles and not all points. So, to do that I think I have to fetch all data first and cut what I want. 

For the following script
```
import yt
from darksky_catalog import darksky
ds = darksky["ds14_a"].load()
p = yt.ProjectionPlot(ds, 0, 'dark_matter')
p.save() 
```

I get a MemoryError message as below

```
yt : [INFO     ] 2019-01-22 23:52:02,532 Building memmap with offset: 2528 and size 65536
yt : [INFO     ] 2019-01-22 23:52:03,653 Building memmap with offset: 1575392 and size 1073741824000
yt : [INFO     ] 2019-01-22 23:52:04,779 Calculating time to be 4.342e+17 seconds
yt : [INFO     ] 2019-01-22 23:52:04,891 Parameters: current_time              = 4.342058717540864e+17
yt : [INFO     ] 2019-01-22 23:52:04,891 Parameters: domain_dimensions         = [2 2 2]
yt : [INFO     ] 2019-01-22 23:52:04,891 Parameters: domain_left_edge          = [-5813429.5 -5813429.5 -5813429.5]
yt : [INFO     ] 2019-01-22 23:52:04,892 Parameters: domain_right_edge         = [5813429.5 5813429.5 5813429.5]
yt : [INFO     ] 2019-01-22 23:52:04,892 Parameters: cosmological_simulation   = 1
yt : [INFO     ] 2019-01-22 23:52:04,892 Parameters: current_redshift          = 0.0
yt : [INFO     ] 2019-01-22 23:52:04,892 Parameters: omega_lambda              = 0.7048737821671822
yt : [INFO     ] 2019-01-22 23:52:04,892 Parameters: omega_matter              = 0.2951262178328177
yt : [INFO     ] 2019-01-22 23:52:04,892 Parameters: hubble_constant           = 0.6880620000000001
yt : [INFO     ] 2019-01-22 23:52:04,898 Allocating for 1.074e+12 particles (index particle type 'all')
Traceback (most recent call last):
  File "darksky.py", line 4, in <module>
    p = yt.ProjectionPlot(ds, 0, 'dark_matter')
  File "/home/mahmood/.local/lib/python2.7/site-packages/yt/visualization/plot_window.py", line 1464, in __init__
    validate_mesh_fields(test_data_source, fields)
  File "/home/mahmood/.local/lib/python2.7/site-packages/yt/visualization/plot_window.py", line 132, in validate_mesh_fields
    canonical_fields = data_source._determine_fields(fields)
  File "/home/mahmood/.local/lib/python2.7/site-packages/yt/data_objects/data_containers.py", line 1165, in _determine_fields
    finfo = self.ds._get_field_info("unknown", fname)
  File "/home/mahmood/.local/lib/python2.7/site-packages/yt/data_objects/static_output.py", line 756, in _get_field_info
    self.index
  File "/home/mahmood/.local/lib/python2.7/site-packages/yt/data_objects/static_output.py", line 509, in index
    self, dataset_type=self.dataset_type)
  File "/home/mahmood/.local/lib/python2.7/site-packages/yt/geometry/particle_geometry_handler.py", line 39, in __init__
    super(ParticleIndex, self).__init__(ds, dataset_type)
  File "/home/mahmood/.local/lib/python2.7/site-packages/yt/geometry/geometry_handler.py", line 50, in __init__
    self._setup_geometry()
  File "/home/mahmood/.local/lib/python2.7/site-packages/yt/geometry/particle_geometry_handler.py", line 50, in _setup_geometry
    self._initialize_particle_handler()
  File "/home/mahmood/.local/lib/python2.7/site-packages/yt/geometry/particle_geometry_handler.py", line 104, in _initialize_particle_handler
    self._initialize_indices()
  File "/home/mahmood/.local/lib/python2.7/site-packages/yt/geometry/particle_geometry_handler.py", line 126, in _initialize_indices
    morton = np.empty(self.total_particles, dtype="uint64")
MemoryError

```

And for the following script
```
import yt
ds14_a = yt.load("http://darksky.slac.stanford.edu/simulations/ds14_a/ds14_a_1.0000")
print "Number of particles: %i" % ds14_a['npart']
```
I get this output
```
yt : [INFO     ] 2019-01-22 23:54:04,295 Building memmap with offset: 2528 and size 65536
yt : [INFO     ] 2019-01-22 23:54:05,424 Building memmap with offset: 1575392 and size 1073741824000
yt : [INFO     ] 2019-01-22 23:54:06,519 Calculating time to be 4.342e+17 seconds
yt : [INFO     ] 2019-01-22 23:54:06,586 Parameters: current_time              = 4.342058717540864e+17
yt : [INFO     ] 2019-01-22 23:54:06,586 Parameters: domain_dimensions         = [2 2 2]
yt : [INFO     ] 2019-01-22 23:54:06,587 Parameters: domain_left_edge          = [-5813429.5 -5813429.5 -5813429.5]
yt : [INFO     ] 2019-01-22 23:54:06,587 Parameters: domain_right_edge         = [5813429.5 5813429.5 5813429.5]
yt : [INFO     ] 2019-01-22 23:54:06,587 Parameters: cosmological_simulation   = 1
yt : [INFO     ] 2019-01-22 23:54:06,587 Parameters: current_redshift          = 0.0
yt : [INFO     ] 2019-01-22 23:54:06,587 Parameters: omega_lambda              = 0.7048737821671822
yt : [INFO     ] 2019-01-22 23:54:06,587 Parameters: omega_matter              = 0.2951262178328177
yt : [INFO     ] 2019-01-22 23:54:06,587 Parameters: hubble_constant           = 0.6880620000000001
Number of particles: 1073741824000

```

Nothing is saved in my computer. Can someone help? Thanks

**Comment by mahmoodn** [comment]
Thanks for the fast reply. Can you explain more about **_select the subvolume you'd like to project_**?
I am new to yt. If that is pointed out in a document, please let me know.

**Comment by ngoldbaum** [comment]
Use a data object to select a subvolume of the dataset. You can then visualize the subvolume with `ProjectionPlot` by passing the data object via the `data_source` keyword argument to `ProjectionPlot`:

```
from yt.units import Mpc
center = ds.domain_center  # or the location of some halo
box = ds.box(center - 50*Mpc, center + 50*mpc)
plot = yt.ProjectionPlot(ds, 'z', ('deposit', 'all_cic'), data_source=box)
plot.save()
```

For more information about data objects, see: http://yt-project.org/doc/analyzing/objects.html

**Comment by ngoldbaum** [comment]
It also looks like you're not loading the data via thingking using the `midx` index file. You may want to ensure you're doing that.

**Comment by mahmoodn** [comment]
I read that. However, there are still many dark points in my mind. 
1- The following script fails
```
from yt.units import Mpc
center = ds.domain_center  # or the location of some halo
box = ds.box(center - 50*Mpc, center + 50*mpc)
plot = yt.ProjectionPlot(ds, 'z', ('deposit', 'all_cic'), data_source=box)
plot.save()

```
and the error is
```
$ python3.6 darksky.py 
Traceback (most recent call last):
  File "darksky.py", line 2, in <module>
    center = ds.domain_center  # or the location of some halo
NameError: name 'ds' is not defined

```
Even with 2.7, I get that error.


2- I have a text file which has 1M lines like this

```
-5813186.5 -5812532 -5812871 -121.615906 90.6227341 -285.711761
-5813311.5 -5812157.5 -5812351 -78.003334 67.453331 -302.702393

```
and it is said to be the first 1M points of http://darksky.slac.stanford.edu/edr.html
I tried to run two scripts but I don't get any data file.

3- It seems that I have to fetch part of the http://darksky.slac.stanford.edu/simulations/ds14_a/ds14_a_1.0000 however, that is a binary file and not a plain array text file.

Can you explain where should I go?

**Comment by ngoldbaum** [comment]
I gave you a snippet of a script, you need to load a dataset first.

I'm sorry but I can't provide detailed support on working with the dark skies data.
