### ISSUE TITLE
mapserver doesn't find js files

### ISSUE THREAD

**Issue by eteq** [yt-project/yt#2157]
### Bug report

**Bug summary**

When I try to run the mapserver on a (stable) conda install of yt, I get ``No such file or directory: '.../lib/python3.7/site-packages/yt/visualization/mapserver/html/map.js'``

**Code for reproduction**

``yt mapserver <any data file>``

and then try to go to the relevant local URL

**Actual outcome**

```
Traceback (most recent call last):
  File ".../bin/bottle.py", line 862, in _handle
    return route.call(**args)
  File ".../bin/bottle.py", line 1740, in wrapper
    rv = callback(*a, **ka)
  File ".../lib/python3.7/site-packages/yt/visualization/mapserver/pannable_map.py", line 135, in static
    return open(full_path, 'r').read()
FileNotFoundError: [Errno 2] No such file or directory: '.../lib/python3.7/site-packages/yt/visualization/mapserver/html/Leaflet.Coordinates-0.1.5.src.js'
127.0.0.1 - - [25/Feb/2019 15:13:57] "GET /static/Leaflet.Coordinates-0.1.5.src.js HTTP/1.1" 500 1608
Traceback (most recent call last):
  File ".../bin/bottle.py", line 862, in _handle
    return route.call(**args)
  File ".../bin/bottle.py", line 1740, in wrapper
    rv = callback(*a, **ka)
  File ".../lib/python3.7/site-packages/yt/visualization/mapserver/pannable_map.py", line 135, in static
    return open(full_path, 'r').read()
FileNotFoundError: [Errno 2] No such file or directory: '.../lib/python3.7/site-packages/yt/visualization/mapserver/html/Leaflet.Coordinates-0.1.5.css'
127.0.0.1 - - [25/Feb/2019 15:13:57] "GET /static/Leaflet.Coordinates-0.1.5.css HTTP/1.1" 500 1602
Traceback (most recent call last):
  File ".../bin/bottle.py", line 862, in _handle
    return route.call(**args)
  File ".../bin/bottle.py", line 1740, in wrapper
    rv = callback(*a, **ka)
  File ".../lib/python3.7/site-packages/yt/visualization/mapserver/pannable_map.py", line 135, in static
    return open(full_path, 'r').read()
FileNotFoundError: [Errno 2] No such file or directory: '.../lib/python3.7/site-packages/yt/visualization/mapserver/html/map.js'
127.0.0.1 - - [25/Feb/2019 15:13:57] "GET /static/map.js HTTP/1.1" 500 1556
Traceback (most recent call last):
  File ".../bin/bottle.py", line 862, in _handle
    return route.call(**args)
  File ".../bin/bottle.py", line 1740, in wrapper
    rv = callback(*a, **ka)
  File ".../lib/python3.7/site-packages/yt/visualization/mapserver/pannable_map.py", line 135, in static
    return open(full_path, 'r').read()
FileNotFoundError: [Errno 2] No such file or directory: '.../lib/python3.7/site-packages/yt/visualization/mapserver/html/Leaflet.Coordinates-0.1.5.src.js'
127.0.0.1 - - [25/Feb/2019 15:13:58] "GET /static/Leaflet.Coordinates-0.1.5.src.js HTTP/1.1" 500 1608
Traceback (most recent call last):
  File ".../bin/bottle.py", line 862, in _handle
    return route.call(**args)
  File ".../bin/bottle.py", line 1740, in wrapper
    rv = callback(*a, **ka)
  File ".../lib/python3.7/site-packages/yt/visualization/mapserver/pannable_map.py", line 135, in static
    return open(full_path, 'r').read()
FileNotFoundError: [Errno 2] No such file or directory: '.../lib/python3.7/site-packages/yt/visualization/mapserver/html/Leaflet.Coordinates-0.1.5.css'
127.0.0.1 - - [25/Feb/2019 15:13:58] "GET /static/Leaflet.Coordinates-0.1.5.css HTTP/1.1" 500 1602
Traceback (most recent call last):
  File ".../bin/bottle.py", line 862, in _handle
    return route.call(**args)
  File ".../bin/bottle.py", line 1740, in wrapper
    rv = callback(*a, **ka)
  File ".../lib/python3.7/site-packages/yt/visualization/mapserver/pannable_map.py", line 135, in static
    return open(full_path, 'r').read()
FileNotFoundError: [Errno 2] No such file or directory: '.../lib/python3.7/site-packages/yt/visualization/mapserver/html/map.js'
```

**Expected outcome**

The mapserver should have come up 

**Version Information**

  * Operating System: OS X 10.11
  * Python Version: 3.7
  * yt version: 3.5.0
  * Other Libraries (if applicable): Chrome 71.0.3578.98

Installed from conda-forge

**Comment by ngoldbaum** [comment]
That's odd, I guess we need to manually make sure the javascript ends up in the conda package.

**Comment by eteq** [comment]
Thanks @ngoldbaum - Should have added: this is what's in the relevent directory:
```
__init__.py    __pycache__    map_index.html
```
Note the presence of `map_index.html`... I wonder if this might be a `MANIFEST` problem? (bearing in mind I don't really know anything about what the build process is for the js files...)

**Comment by ngoldbaum** [comment]
So I think what happened is https://github.com/yt-project/yt/pull/1668/files removed our vendored copy of leaflet.js, but there's some other javascript that should also be included in the sdist and is now not.

**Comment by eteq** [comment]
One more troubleshooting hint: if I copy the .js and .css files from the *source* tree of yt into the `mapserver/html` directory, all seems to work perfectly.
