### ISSUE TITLE
local deposited particle fields don't work in yt-4.0 for particle datasets

### ISSUE THREAD

**Issue by ngoldbaum** [yt-project/yt#2192]
### Bug report

**Bug summary**

Trying to plot a field like `('deposit', 'stars_cic')` will raise a `NotImplementedError`. Ultimately this is happening because there's no longer an octree to deposit the particle data onto so presumably we need to deposit directly onto images or do something else.

**Code for reproduction**

You can reproduce this right now by running `particle_filter.py` in the cookbook.

**Actual outcome**

```
Traceback (most recent call last):
  File "/Users/goldbaum/.pyenv/versions/3.7.2/lib/python3.7/pdb.py", line 1697, in main
    pdb._runscript(mainpyfile)
  File "/Users/goldbaum/.pyenv/versions/3.7.2/lib/python3.7/pdb.py", line 1566, in _runscript
    self.run(statement)
  File "/Users/goldbaum/.pyenv/versions/3.7.2/lib/python3.7/bdb.py", line 585, in run
    exec(cmd, globals, locals)
  File "<string>", line 1, in <module>
  File "/Users/goldbaum/Documents/yt-git/doc/source/cookbook/particle_filter.py", line 1, in <module>
    import yt
  File "/Users/goldbaum/Documents/yt-git/yt/visualization/plot_window.py", line 1599, in __init__
    aspect=aspect)
  File "/Users/goldbaum/Documents/yt-git/yt/visualization/plot_window.py", line 777, in __init__
    PlotWindow.__init__(self, *args, **kwargs)
  File "/Users/goldbaum/Documents/yt-git/yt/visualization/plot_window.py", line 234, in __init__
    self._setup_plots()
  File "/Users/goldbaum/Documents/yt-git/yt/visualization/plot_window.py", line 896, in _setup_plots
    image = self.frb[f]
  File "/Users/goldbaum/Documents/yt-git/yt/visualization/fixed_resolution.py", line 135, in __getitem__
    int(self.antialias))
  File "/Users/goldbaum/Documents/yt-git/yt/geometry/coordinates/cartesian_coordinates.py", line 205, in pixelize
    antialias, dimension, periodic)
  File "/Users/goldbaum/Documents/yt-git/yt/geometry/coordinates/cartesian_coordinates.py", line 453, in _ortho_pixelize
    data_source['px'], data_source['py'],
  File "/Users/goldbaum/Documents/yt-git/yt/data_objects/data_containers.py", line 254, in __getitem__
    self.ds.arr(self._generate_container_field(f))
  File "/Users/goldbaum/Documents/yt-git/yt/data_objects/data_containers.py", line 416, in _generate_container_field
    raise NotImplementedError
NotImplementedError
```

**Expected outcome**

A plot of the CIC deposited data

**Comment by ngoldbaum** [comment]
I think the most straightforward way forward here is to make it so `SlicePlot` and `ProjectionPlot` can do local deposit operations directly onto images (e.g. what `ParticlePlot` already does).

**Comment by ngoldbaum** [comment]
Another way to handle this would be to use `ds.octree` and deposit data onto the octree.
