### ISSUE TITLE
cyoctree tests are randomly failing on MacOS

### ISSUE THREAD

**Issue by ngoldbaum** [yt-project/yt#2196]
### Bug report

**Bug summary**

Every once in a while the mac build on travis will randomly fail in a test for cyoctree.

**Code for reproduction**

```bash
nosetests yt/data_objects/tests/test_octree.py
```

**Actual outcome**

Most of the time this passes but everyone once in a while this will fail with the following traceback:

```
======================================================================
ERROR: This builds an octree, writes to file, reloads and ensure that the reloaded
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/goldbaum/.pyenv/versions/3.7.2/lib/python3.7/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/Users/goldbaum/Documents/yt-git/yt/data_objects/tests/test_octree.py", line 43, in test_saving_loading
    octree = ds.octree(n_ref=1)
  File "/Users/goldbaum/Documents/yt-git/yt/data_objects/construction_data_containers.py", line 2194, in __init__
    self.tree
  File "/Users/goldbaum/Documents/yt-git/yt/data_objects/construction_data_containers.py", line 2247, in tree
    self._generate_tree(fname)
  File "/Users/goldbaum/Documents/yt-git/yt/data_objects/construction_data_containers.py", line 2224, in _generate_tree
    self._octree.save(fname)
  File "yt/utilities/lib/cyoctree.pyx", line 533, in yt.utilities.lib.cyoctree.CyOctree.save
  File "yt/utilities/lib/cyoctree.pyx", line 541, in yt.utilities.lib.cyoctree.CyOctree.save
struct.error: argument out of range

----------------------------------------------------------------------
```

**Expected outcome**

Test runs without error

**Version Information**

  * Operating System:
  * Python Version:
  * yt version:
  * Other Libraries (if applicable):

**Comment by ngoldbaum** [comment]
I made the following modification:

```diff
diff --git a/yt/utilities/lib/cyoctree.pyx b/yt/utilities/lib/cyoctree.pyx
index 181f65c92..232556470 100644
--- a/yt/utilities/lib/cyoctree.pyx
+++ b/yt/utilities/lib/cyoctree.pyx
@@ -538,6 +538,8 @@ cdef class CyOctree:
                                 *self.idx))

             for i in range(self.num_octs):
+                print(i)
+                print(self.nodes[i])
                 f.write(struct.pack('6d4Q?2QB',
                                     self.nodes[i].left_edge[0],
                                     self.nodes[i].left_edge[1],
```

The node it fails on looks like this:

```
{'left_edge': [2.25, 0.0, 0.75], 'right_edge': [3.0, 0.75, 1.5], 'start': 33, 'end': 33, 'parent': 5, 'children': -5509011700109604595, 'leaf': True, 'node_id': 38, 'leaf_id': 0, 'depth': 2}
```

So it looks like `children` is either not getting initialized or is getting corrupted somehow. The crash is coming from trying to write a negative number where `struct` is expecting a uint.

@AshKelly if you have a little bit of time and interest it would be cool if you could take a look at this.

**Comment by AshKelly** [comment]
almost certainly to do with this stuff

```struct.pack('2Q3iq'```
or
```struct.pack('6d4Q?2QB'```

I'm happy to check this out

**Comment by ngoldbaum** [comment]
Ah yeah, me too :)

```
diff --git a/yt/utilities/lib/cyoctree.pyx b/yt/utilities/lib/cyoctree.pyx
index 181f65c92..01ccb368a 100644
--- a/yt/utilities/lib/cyoctree.pyx
+++ b/yt/utilities/lib/cyoctree.pyx
@@ -284,6 +284,7 @@ cdef class CyOctree:
         temp.leaf = 1
         temp.depth = node.depth + 1
         temp.leaf_id = 0
+        temp.children = 0

         # Set up the values to be used to set the child boundaries
         dx = (node.right_edge[0] - node.left_edge[0]) / self._num_children_per_dim
```

I'll let you issue the PR :)
