### ISSUE TITLE
Handling Enzo datasets with ghost zones

### ISSUE THREAD

**Issue by cbrummelsmith** [yt-project/yt#2217]
### Bug report

yt is not working with Enzo datasets containing ghost zones, i.e. when using `WriteGhostZones = 1` in Enzo parameter file. I've reproduced the errors using Enzo's `<enzo_dir>/run/Cosmology/AdiabaticExpansion` simulation. The only change I made to the default `AdiabaticExpansion.enzo` parameter file was I added `WriteGhostZones = 1`

**Code for reproduction**

```python
import yt
ds = yt.load('DD0001/data0001')
ad = ds.all_data()
n = ad['density']
```
Here is a link to the dataset
https://girder.hub.yt/#user/5c9593a468085e0001d965cd/folder/5c9595b968085e0001d965d4

**Actual outcome**

When trying to access field data I get one of the following errors. This happens for all the datasets, not just DD0001. I suspect this is a yt problem rather than an problem with Enzo writing the ghost zones because I see no errors or unusual values when inspecting the dataset with h5dump.

```
/anaconda2/lib/python2.7/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
yt : [INFO     ] 2019-03-11 14:53:54,736 Parameters: current_time              = 5.81646932457
yt : [INFO     ] 2019-03-11 14:53:54,736 Parameters: domain_dimensions         = [16 16 16]
yt : [INFO     ] 2019-03-11 14:53:54,737 Parameters: domain_left_edge          = [0. 0. 0.]
yt : [INFO     ] 2019-03-11 14:53:54,737 Parameters: domain_right_edge         = [1. 1. 1.]
yt : [INFO     ] 2019-03-11 14:53:54,737 Parameters: cosmological_simulation   = 1
yt : [INFO     ] 2019-03-11 14:53:54,737 Parameters: current_redshift          = 4.6722468533
yt : [INFO     ] 2019-03-11 14:53:54,738 Parameters: omega_lambda              = 0
yt : [INFO     ] 2019-03-11 14:53:54,738 Parameters: omega_matter              = 1
yt : [INFO     ] 2019-03-11 14:53:54,738 Parameters: hubble_constant           = 1
Parsing Hierarchy : 100%|█████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:00<00:00, 13066.37it/s]
yt : [INFO     ] 2019-03-11 14:53:54,742 Gathering a field list (this may take a moment.)
Traceback (most recent call last):
  File "ghost.py", line 8, in <module>
    n = ad['density']
  File "/anaconda2/lib/python2.7/site-packages/yt/data_objects/data_containers.py", line 282, in __getitem__
    self.get_data(f)
  File "/anaconda2/lib/python2.7/site-packages/yt/data_objects/data_containers.py", line 1325, in get_data
    fluids, self, self._current_chunk)
  File "/anaconda2/lib/python2.7/site-packages/yt/geometry/geometry_handler.py", line 245, in _read_fluid_fields
    chunk_size)
  File "/anaconda2/lib/python2.7/site-packages/yt/utilities/io_handler.py", line 148, in _read_fluid_selection
    ind[field] += obj.select(selector, data, rv[field], ind[field])
  File "/anaconda2/lib/python2.7/site-packages/yt/data_objects/grid_patch.py", line 417, in select
    dest[offset:offset+count, i] = source[sl][mask]
IndexError: boolean index did not match indexed array along dimension 0; dimension is 9 but corresponding boolean dimension is 16
Segmentation fault: 11
```
or
```

/anaconda2/lib/python2.7/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
yt : [INFO     ] 2019-03-11 14:54:00,703 Parameters: current_time              = 5.81646932457
yt : [INFO     ] 2019-03-11 14:54:00,704 Parameters: domain_dimensions         = [16 16 16]
yt : [INFO     ] 2019-03-11 14:54:00,704 Parameters: domain_left_edge          = [0. 0. 0.]
yt : [INFO     ] 2019-03-11 14:54:00,704 Parameters: domain_right_edge         = [1. 1. 1.]
yt : [INFO     ] 2019-03-11 14:54:00,704 Parameters: cosmological_simulation   = 1
yt : [INFO     ] 2019-03-11 14:54:00,704 Parameters: current_redshift          = 4.6722468533
yt : [INFO     ] 2019-03-11 14:54:00,704 Parameters: omega_lambda              = 0
yt : [INFO     ] 2019-03-11 14:54:00,704 Parameters: omega_matter              = 1
yt : [INFO     ] 2019-03-11 14:54:00,704 Parameters: hubble_constant           = 1
Parsing Hierarchy : 100%|█████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:00<00:00, 13888.42it/s]
yt : [INFO     ] 2019-03-11 14:54:00,708 Gathering a field list (this may take a moment.)
python(56950,0x10424b5c0) malloc: Incorrect checksum for freed object 0x108214800: probably modified after being freed.
Corrupt value: 0x3ff00068c52eb963
python(56950,0x10424b5c0) malloc: *** set a breakpoint in malloc_error_break to debug
Abort trap: 6
```

**Expected outcome**

I expect nothing out of the ordinary and for yt to handle Enzo datasets with ghost zones just like normal Enzo datasets without ghost zones.

**Version Information**

  * Operating System: Mac OS 10.14.2
  * Python Version: Python 2.7.15 :: Anaconda, Inc.
  * yt version: 3.5.1

Everything installed with conda. yt installed from
`conda install -c conda-forge yt`

**Comment by ngoldbaum** [comment]
Not terribly surprising given that this functionality is completely untested at the moment.
