### ISSUE TITLE
SDF frontend not working properly

### ISSUE THREAD

**Issue by Xarthisius** [yt-project/yt#2332]
On current master:

```
from yt.frontends.sdf.api import SDFDataset
url =  'http://darksky.slac.stanford.edu/scivis2015/data/ds14_scivis_0128/ds14_scivis_0128_e4_dt04_1.0000'
ds = SDFDataset(url)
```

hangs for a long time, and after a while throws:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "yt/frontends/sdf/data_structures.py", line 104, in __init__
    n_ref=n_ref, over_refine_factor=over_refine_factor)
  File "yt/data_objects/static_output.py", line 1496, in __init__
    units_override=units_override, unit_system=unit_system)
  File "yt/data_objects/static_output.py", line 250, in __init__
    self._parse_parameter_file()
  File "yt/frontends/sdf/data_structures.py", line 112, in _parse_parameter_file
    header=self.sdf_header)
  File "yt/utilities/sdf.py", line 466, in __init__
    super(HTTPSDFRead, self).__init__(*args, **kwargs)
  File "yt/utilities/sdf.py", line 295, in __init__
    self.parse_header()
  File "yt/utilities/sdf.py", line 473, in parse_header
    lines = cStringIO(ascfile[:max_header_size].data[:])
TypeError: initial_value must be str or None, not memoryview
```

**Comment by Xarthisius** [comment]
On that note, this test seems to pass occasionally on Travis but takes really long time:

```
test_outputs.test_scivis ... ok (599.3647s)
```

**Comment by matthewturk** [comment]
Wow -- looks like maybe rate-limiting from SLAC?  We should perhaps either
disable, or point to a different URL.

**Comment by matthewturk** [comment]
Funnily enough, `.tostring()` now provides bytes and it also hates that, so hooray!

What I think works is:

```
lines = cStringIO(ascfile[:max_header_size].tostring().decode('ascii', errors='ignore'))
```

Since we're actually interpreting it as ASCII (this is for the header) we can get away with this.

**Comment by munkm** [comment]
https://github.com/yt-project/yt/pull/2334 addressed this temporarily.

**Comment by Xarthisius** [comment]
Cause was external to yt. Closing.
