### ISSUE TITLE
Unexpected errors when passing wrong shape to YTSphere

### ISSUE THREAD

**Issue by cphyc** [yt-project/yt#2393]
### Bug report

**Bug summary**

When building a YTSphere object with a centre with a shape (1, 3), yt subsequently fails with cryptic messages.

**Code for reproduction**

```python
ds = yt.load('output_00080/info_00080.txt')
@yt.particle_filter(name='single', requires=['particle_identity'], filtered_type='io') 
def _filter(pfilter, data): 
    ptype = pfilter.filtered_type 
    return (data[ptype, 'particle_identity'] == 2) & (data[ptype, 'particle_mass'] > 3e-7)
ds.add_particle_filter('single')

centre = ds.r['single', 'particle_position']  # has shape (1, 3)
ad = ds.all_data()
sp = ds.sphere(centre, (100, 'kpc'))

sp['density']  # Fails with: TypeError: only size-1 arrays can be converted to Python scalars
ad - sp  # Fails with TypeError: Cannot convert YTSphere to yt.geometry.selection_routines.SelectorObject

```

**Actual outcome**

For `sp['density']`
```
Traceback (most recent call last):
  File "/tmp/fail.py", line 13, in <module>
    sp['density']
  File "/home/ccc/Documents/prog/yt/yt/data_objects/data_containers.py", line 256, in __getitem__
    self.get_data(f)
  File "/home/ccc/Documents/prog/yt/yt/data_objects/data_containers.py", line 1482, in get_data
    self.index._identify_base_chunk(self)
  File "/home/ccc/Documents/prog/yt/yt/frontends/ramses/data_structures.py", line 277, in _identify_base_chunk
    domains = [dom for dom in self.domains if
  File "/home/ccc/Documents/prog/yt/yt/frontends/ramses/data_structures.py", line 278, in <listcomp>
    dom.included(dobj.selector)]
  File "/home/ccc/Documents/prog/yt/yt/data_objects/data_containers.py", line 1434, in selector
    self._selector = sclass(self)
  File "yt/geometry/selection_routines.pyx", line 717, in yt.geometry.selection_routines.SphereSelector.__init__
    self.center[i] = _ensure_code(dobj.center[i])
TypeError: only size-1 arrays can be converted to Python scalars
```
For `ad-sp`:
```
Traceback (most recent call last):
  File "/tmp/fail.py", line 13, in <module>
    ad-sp
  File "/home/ccc/Documents/prog/yt/yt/data_objects/data_containers.py", line 1653, in __sub__
    return YTBooleanContainer("NEG", self, other, ds = self.ds)
  File "/home/ccc/Documents/prog/yt/yt/data_objects/data_containers.py", line 2686, in __init__
    self._selector = sel_cls(self)
  File "yt/geometry/selection_routines.pyx", line 2124, in yt.geometry.selection_routines.BooleanSelector.__init__
    self.sel2 = dobj.dobj2
TypeError: Cannot convert YTSphere to yt.geometry.selection_routines.SelectorObject

```
**Expected outcome**

Yt should detect the unexpected shape and either raise a warning and reshape it to `(3,)`, or raise an Exception to prevent the weird errors from being raised later. 

**Version Information**
  * Operating System: Linux
  * Python Version: 3.7.4 
  * yt version: 3.6.dev0

**Comment by munkm** [comment]
closed via yt-project/yt#2888
