### ISSUE TITLE
Bug in multi_plot with ProjectionPlots. 

### ISSUE THREAD

**Issue by Anikbh11** [yt-project/yt#2455]
### Bug report

**Bug summary**

Trying to create multiplot projections using yt4.0 using the exact code (multi_plot_slice_and_proj.py) in the cookbook (https://yt-project.org/doc/cookbook/complex_plots.html). Both my code to project column densities and the code as given in the cookbook crash 
**Code for reproduction**

```python
# Paste your code here
#
#
```
import yt
import trident 
import matplotlib.pyplot as plt
from yt.utilities.physical_constants import mh
from yt.visualization.base_plot_types import get_multi_plot
import matplotlib.colorbar as cb
from matplotlib.colors import LogNorm
import numpy as np

yt.enable_parallelism()

def _nhi(field,data):
    return ((data[('PartType0','Density')] * data[('PartType0','Hydrogen')] * data[('PartType0','apHI')])/mh)

path = '/afs/mpa/temp/mrmgehlm/Aurora/snapshot_052/'
ds = yt.load(path+'snap_052.0.hdf5')
ds.add_field("H_p0_number_density",sampling_type='particle',function=_nhi,units="1/cm**3",force_override=True)

trident.add_ion_fields(ds,ions = ['O I','C II','Si II','Fe II'],sampling_type='particle')

orient = 'horizontal'
fig, axes, colorbars = get_multi_plot(3,2,colorbar=orient,bw=6)

center = ds.domain_center

left_corner = ds.domain_left_edge
right_corner = ds.domain_right_edge
depth = ds.quan(1.0,'code_length')
left_corner[2] = center[2] - 0.5 * depth
right_corner[2] = center[2] + 0.5 * depth
region = ds.box(left_corner, right_corner)

res = [1200,1200]
width = (6.25,'code_length')
width1 = (0.7,'code_length')

vv,cc = ds.find_max("H_p0_number_density")

left = cc 
right = cc 
depth1 = ds.quan(0.75,'code_length')
left = left - depth1
right = right + depth1

reg = ds.box(left,right)

slc = yt.ProjectionPlot(ds, "z", fields=["H_p0_number_density","O_p0_number_density","C_p1_number_density"], weight_field=None,data_source=region)

proj = yt.ProjectionPlot(ds, "z", fields=["H_p0_number_density","O_p0_number_density","C_p1_number_density"], weight_field=None,data_source=reg)

#proj = yt.SlicePlot(ds,'z',"H_p0_number_density",center=cc,width=(0.7,'code_length'))

slc_frb = slc.data_source.to_frb(width,res)
proj_frb = proj.data_source.to_frb(width1,res)

dens_axes = [axes[0][0], axes[1][0]]
temp_axes = [axes[0][1], axes[1][1]]
vels_axes = [axes[0][2], axes[1][2]]

for dax, tax, vax in zip(dens_axes, temp_axes, vels_axes) :

    dax.xaxis.set_visible(False)
    dax.yaxis.set_visible(False)
    tax.xaxis.set_visible(False)
    tax.yaxis.set_visible(False)
    vax.xaxis.set_visible(False)
    vax.yaxis.set_visible(False)

slc_dens = np.array(slc_frb[('gas','H_p0_number_density')])
proj_dens = np.array(proj_frb[('gas','H_p0_number_density')])
slc_temp = np.array(slc_frb[('gas','O_p0_number_density')])
proj_temp = np.array(proj_frb[('gas','O_p0_number_density')])
slc_vel = np.array(slc_frb[('gas','C_p1_number_density')])
proj_vel = np.array(proj_frb[('gas','C_p1_number_density')])

plots = [dens_axes[0].imshow(slc_dens, origin='lower', norm=LogNorm()),
         dens_axes[1].imshow(proj_dens, origin='lower', norm=LogNorm()),
         temp_axes[0].imshow(slc_temp, origin='lower'),
         temp_axes[1].imshow(proj_temp, origin='lower'),
         vels_axes[0].imshow(slc_vel, origin='lower', norm=LogNorm()),
         vels_axes[1].imshow(proj_vel, origin='lower', norm=LogNorm())]

plots[0].set_clim((1.0e15,1.0e24))
plots[0].set_cmap("dusk")
plots[1].set_clim((1.0e15,1.0e24))
plots[1].set_cmap("dusk")
plots[2].set_clim((1.0e12,1.0e20))
plots[2].set_cmap("dusk")
plots[3].set_clim((1.0e12,1.0e20))
plots[3].set_cmap("dusk")
plots[4].set_clim((1e12, 1e20))
plots[4].set_cmap("dusk")
plots[5].set_clim((1e12, 1e20))
plots[5].set_cmap("dusk")

titles=[r'$\mathrm{H\ I\ Column\ Density}\ (\mathrm{cm^{-2}})$',
        r'$\mathrm{O\ I\ Column\ Density\}\ (\mathrm{cm^{-2}})$',
        r'$\mathrm{C\ II\ Column\ Density\}\ (\mathrm{cm^{-2}})$']

for p, cax, t in zip(plots[0:6:2], colorbars, titles):
    cbar = fig.colorbar(p, cax=cax, orientation=orient)
    cbar.set_label(t)

fig.savefig("%s_3x2" % ds)

**Actual outcome**

```
# If applicable, paste the console output here
#
#
```
P009 yt : [INFO     ] 2020-02-19 18:22:58,212 Making a fixed resolution buffer of (H_p0_number_density) 1200 by 1200
  File "trident_projection.py", line 69, in <module>
    slc_dens = np.array(slc_frb['H_p0_number_density'])
  File "/afs/mpa/temp/mrmgehlm/yt-yt-4.0/yt/visualization/fixed_resolution.py", line 136, in __getitem__
    units = self.data_source[item].units
  File "/afs/mpa/temp/mrmgehlm/yt-yt-4.0/yt/data_objects/data_containers.py", line 266, in __getitem__
    rv = self.ds.arr(self.field_data[key], fi.units)
P014 yt : [ERROR    ] 2020-02-19 18:23:13,608 KeyError: 'H_p0_number_density'
P014 yt : [ERROR    ] 2020-02-19 18:23:13,608 Error occured on rank 14.
application called MPI_Abort(MPI_COMM_WORLD, 1) - process 14

**Expected outcome**
A multiplot with 2 rows and 3 columns 

**Version Information**

  * Operating System: linux 
  * Python Version: Python 3.6.8
  * yt version: 4.0.dev0
  * Other Libraries (if applicable):  Trident : 1.3.dev1

Downloaded the 4.0 branch and pip install -e .

**Comment by neutrinoceros** [comment]
Hi there ! Thanks a lot for taking the time to report this problem. To help us reproduce this, could you please give a more concise, minimal example script ?
It would also be helpful to know what frontend you are using here (what's the code your input data was produced with ?). That way we should be able to reproduce this crash using a public dataset from https://yt-project.org/data/ (if you can name one that should behave the same as your private dataset already, it's even better !).

**Comment by ngoldbaum** [comment]
So I'm able to run `multi_plot_size_and_proj.py` on the current tip of the yt-4.0 (66d5c9754) branch:

```
$ python multi_plot_slice_and_proj.py
yt : [INFO     ] 2020-02-19 14:17:08,455 Parameters: current_time              = 1.1835090993823291e+17
yt : [INFO     ] 2020-02-19 14:17:08,455 Parameters: domain_dimensions         = [16 16 16]
yt : [INFO     ] 2020-02-19 14:17:08,456 Parameters: domain_left_edge          = [-3.70272e+24 -3.70272e+24 -3.70272e+24]
yt : [INFO     ] 2020-02-19 14:17:08,456 Parameters: domain_right_edge         = [3.70272e+24 3.70272e+24 3.70272e+24]
yt : [INFO     ] 2020-02-19 14:17:08,456 Parameters: cosmological_simulation   = 0.0
yt : [INFO     ] 2020-02-19 14:17:09,801 xlim = -3702719999999999882559488.000000 3702719999999999882559488.000000
yt : [INFO     ] 2020-02-19 14:17:09,801 ylim = -3702719999999999882559488.000000 3702719999999999882559488.000000
yt : [INFO     ] 2020-02-19 14:17:09,802 xlim = -3702719999999999882559488.000000 3702719999999999882559488.000000
yt : [INFO     ] 2020-02-19 14:17:09,802 ylim = -3702719999999999882559488.000000 3702719999999999882559488.000000
yt : [INFO     ] 2020-02-19 14:17:09,802 Making a fixed resolution buffer of (('gas', 'density')) 800 by 800
yt : [INFO     ] 2020-02-19 14:17:09,860 Making a fixed resolution buffer of (('gas', 'temperature')) 800 by 800
yt : [INFO     ] 2020-02-19 14:17:09,880 Making a fixed resolution buffer of (('gas', 'velocity_magnitude')) 800 by 800
yt : [INFO     ] 2020-02-19 14:17:11,427 Projection completed
yt : [INFO     ] 2020-02-19 14:17:11,427 xlim = -3702719999999999882559488.000000 3702719999999999882559488.000000
yt : [INFO     ] 2020-02-19 14:17:11,427 ylim = -3702719999999999882559488.000000 3702719999999999882559488.000000
yt : [INFO     ] 2020-02-19 14:17:11,428 xlim = -3702719999999999882559488.000000 3702719999999999882559488.000000
yt : [INFO     ] 2020-02-19 14:17:11,428 ylim = -3702719999999999882559488.000000 3702719999999999882559488.000000
yt : [INFO     ] 2020-02-19 14:17:11,428 Making a fixed resolution buffer of (('gas', 'density')) 800 by 800
yt : [INFO     ] 2020-02-19 14:17:11,549 Making a fixed resolution buffer of (density) 512 by 512
yt : [INFO     ] 2020-02-19 14:17:11,563 Making a fixed resolution buffer of (density) 512 by 512
yt : [INFO     ] 2020-02-19 14:17:11,580 Making a fixed resolution buffer of (temperature) 512 by 512
yt : [INFO     ] 2020-02-19 14:17:11,595 Making a fixed resolution buffer of (temperature) 512 by 512
yt : [INFO     ] 2020-02-19 14:17:12,220 Projection completed
yt : [INFO     ] 2020-02-19 14:17:12,246 Making a fixed resolution buffer of (velocity_magnitude) 512 by 512
yt : [INFO     ] 2020-02-19 14:17:12,262 Making a fixed resolution buffer of (velocity_magnitude) 512 by 512
yt : [INFO     ] 2020-02-19 14:17:13,250 Projection completed
```

You mentioned on slack that it failed for you - did you make any edits to that script to make it fail (e.g. loading a different dataset)?

**Comment by Anikbh11** [comment]
Hey, 

Apologies for my delayed response and incomplete info. I'm using Gadget OWLS multi-file snapshots for my codes. And I used the same snapshot to run the  `multi_plot_size_and_proj.py`

Here's a compact code of what I'm trying to achieve : 

`
fig, ax = plt.subplots(3,1)
proj = yt.ProjectionPlot(ds, "z", fields = ["H_p0_number_density","O_p0_number_density","C_p1_number_density"], weight_field=None)

proj_frb = proj.data_source.to_frb(width1,res)

nhi = np.array(proj_frb['H_p0_number_density'])
noi = np.array(proj_frb['O_p0_number_density'])
ncii = np.array(proj_frb['C_p1_number_density'])

ax[0].imshow(nhi,origin='lower',norm=LogNorm())
ax[1].imshow(noi,origin='lower',norm=LogNorm())
ax[2].imshow(ncii,origin='lower',norm=LogNorm())

fig.savefig('Projection.png')
`

This crashes at the `nhi = np.array(proj_frb['H_p0_number_density'])` line. As Nathan suggested in slack yesterday, if I change the string to `('gas','H_p0_number_density')` the script runs just fine. I figured just 'H_p0_number_density' should do the trick. Am I right in thinking this? 

On a side note, if there a way I can use the annotate_scale() feature here? I'm guessing it won't work in this case since I'm convering the projection plot to numpy ndarrays.

**Comment by ngoldbaum** [comment]
> This crashes at the nhi = np.array(proj_frb['H_p0_number_density']) line. As Nathan suggested in slack yesterday, if I change the string to ('gas','H_p0_number_density') the script runs just fine.

Thanks!

> On a side note, if there a way I can use the annotate_scale() feature here? I'm guessing it won't work in this case since I'm convering the projection plot to numpy ndarrays.

Nope, you'll need to do what the scale plot callback does manually: https://github.com/yt-project/yt/blob/master/yt/visualization/plot_modifications.py#L2343-L2418

(basically, create an AnchoredSizeBar and add the bar to the plot with axes.add_artist)

**Comment by Anikbh11** [comment]
Ah okay, that makes sense thanks! 

Just curious, the code should ideally work with `'H_p0_number_density' instead of ('gas','H_p0_number_density')` too right?

**Comment by ngoldbaum** [comment]
Yup, there are some internal helpers we use to go from a string field name to a field tuple, there's probably just a place where we aren't using those helpers but should be.

**Comment by Anikbh11** [comment]
Alright, thanks! I appreciate your help!

**Comment by ngoldbaum** [comment]
I was able to reproduce this by running making the following change:

```
diff --git a/doc/source/cookbook/multi_plot_slice_and_proj.py b/doc/source/cookbook/multi_plot_slice_and_proj.py
index 1108f81a5..e7de30c87 100644
--- a/doc/source/cookbook/multi_plot_slice_and_proj.py
+++ b/doc/source/cookbook/multi_plot_slice_and_proj.py
@@ -4,7 +4,7 @@ from yt.visualization.base_plot_types import get_multi_plot
 import matplotlib.colorbar as cb
 from matplotlib.colors import LogNorm

-fn = "GasSloshing/sloshing_nomag2_hdf5_plt_cnt_0150" # dataset to load
+fn = "GadgetDiskGalaxy/snapshot_200.hdf5" # dataset to load
 orient = 'horizontal'

 ds = yt.load(fn) # load data
```

In this case the issue is that both `('PartType0', 'density')` and `('gas', 'density')` are valid fields, but the keys of the `_field_transform` dict use the former:

```
Traceback (most recent call last):
  File "/home/goldbaum/.pyenv/versions/3.7.3/lib/python3.7/pdb.py", line 1701, in
 main
    pdb._runscript(mainpyfile)
  File "/home/goldbaum/.pyenv/versions/3.7.3/lib/python3.7/pdb.py", line 1570, in
 _runscript
    self.run(statement)
  File "/home/goldbaum/.pyenv/versions/3.7.3/lib/python3.7/bdb.py", line 585, in
run
    exec(cmd, globals, locals)
  File "<string>", line 1, in <module>
  File "/home/goldbaum/Documents/yt/doc/source/cookbook/multi_plot_slice_and_proj
.py", line 1, in <module>
    import yt
  File "/home/goldbaum/Documents/yt/yt/visualization/plot_window.py", line 2120,
in SlicePlot
    return AxisAlignedSlicePlot(ds, normal, fields, *args, **kwargs)
  File "/home/goldbaum/Documents/yt/yt/visualization/plot_window.py", line 1417,
in __init__
    right_handed=right_handed, buff_size=buff_size)
  File "/home/goldbaum/Documents/yt/yt/visualization/plot_window.py", line 782, i
n __init__
    PlotWindow.__init__(self, *args, **kwargs)
  File "/home/goldbaum/Documents/yt/yt/visualization/plot_window.py", line 217, i
n __init__
    self._setup_plots()
  File "/home/goldbaum/Documents/yt/yt/visualization/plot_window.py", line 902, i
n _setup_plots
    if self._field_transform[f] == log_transform:
KeyError: ('gas', 'density')
Uncaught exception. Entering post mortem debugging
Running 'cont' or 'step' will restart the program
> /home/goldbaum/Documents/yt/yt/visualization/plot_window.py(902)_setup_plots()
-> if self._field_transform[f] == log_transform:
(Pdb) print(self._field_transform.keys())
dict_keys([('PartType0', 'density'), ('PartType0', 'temperature'), ('PartType0',
'velocity_magnitude')])
```

One way to fix this would be to check if a field is an alias and then replace the field name of the alias field with the field name of the original field.
