### ISSUE TITLE
Generic AMR loader fail to find cell edge & grid edge alignment

### ISSUE THREAD

**Issue by caicairay** [yt-project/yt#2665]
### Bug report

**Bug summary**
Generic AMR loader fail to find cell edge & grid edge alignment
Giving error: 
`yt.utilities.exceptions.YTIllDefinedAMR: Grids on the level 2 are not properly aligned with cell edges on the parent level (x axis)`

At line 905 in data_structures.py, it trying to find cell edge & grid edge alignment by set subtraction. But somehow array generated by Numpy linspace is not considered as the same as manually inputted array. 
**Code for reproduction**

```python
>>> list1 = np.linspace(0,1.,10,endpoint=False)
>>> list1
array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])
>>> list2 = np.array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])
>>> set(list1)-set(list2)
{0.30000000000000004, 0.6000000000000001, 0.7000000000000001}
```
Force data type to be the same seems solve the problem.
```python
>>> list1 = np.linspace(0,1.,10,endpoint=False,dtype=np.float32)
>>> list2 = np.array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9]).astype(np.float32)
>>> set(list1) - set(list2)
set()
```
**Version Information**

  * Operating System: OSX Catalina
  * Python Version:      Python 3.7.3
  * yt version:               3.6.dev0
  * Other Libraries (if applicable):

**Comment by neutrinoceros** [comment]
Hi, could you specify which frontend you are using, please ? `data_structure.py` is the name of many files in yt, one for each frontend.
Also, it'd be really helpful to see the code that's actually triggering the error. :-)

**Comment by caicairay** [comment]
Hi, it is the `stream` frontend. Sorry I didn't realise there are so many `data_structure` files.

I tried to reproduce the error in a short script,
```python
import numpy as np
import yt

grid_data = [
    dict(left_edge =[0.0, 0.0, 0.0],
         right_edge=[0.045,0.045,0.045],
         level=0,
         dimensions=[16,16,16]),
    dict(left_edge =[0.0225, 0.0225, 0.0225],
         right_edge=[0.045, 0.045, 0.045],
         level=1,
         dimensions=[16,16,16])
]

for g in grid_data:
    g["density"] = np.random.random(g["dimensions"]) * 2 ** g["level"]

bbox = np.array([[-0.18,0.18],[-0.18,0.18],[-0.18,0.18]])
dimensions = [128,128,128]
ds = yt.load_amr_grids(grid_data, dimensions, bbox)
```

it gives error
```
Traceback (most recent call last):
  File "./reproduce_error.py", line 21, in <module>
    ds = yt.load_amr_grids(grid_data, dimensions, bbox)
  File "/Users/dra/anaconda3/envs/py37_astropy/lib/python3.7/site-packages/yt/frontends/stream/data_structures.py", line 917, in load_amr_grids
    raise YTIllDefinedAMR(lvl, ax)
yt.utilities.exceptions.YTIllDefinedAMR: Grids on the level 1 are not properly aligned with cell edges on the parent level (x axis)
```

I printed out `grid_left_edges[idx,iax]`, `cell_edges` and `set(grid_left_edges[idx, iax]) - set(cell_edges)`
they are 
```
[0.0225]
[-0.18      -0.1771875 -0.174375  -0.1715625 -0.16875   -0.1659375
 -0.163125  -0.1603125 -0.1575    -0.1546875 -0.151875  -0.1490625
 -0.14625   -0.1434375 -0.140625  -0.1378125 -0.135     -0.1321875
 -0.129375  -0.1265625 -0.12375   -0.1209375 -0.118125  -0.1153125
 -0.1125    -0.1096875 -0.106875  -0.1040625 -0.10125   -0.0984375
 -0.095625  -0.0928125 -0.09      -0.0871875 -0.084375  -0.0815625
 -0.07875   -0.0759375 -0.073125  -0.0703125 -0.0675    -0.0646875
 -0.061875  -0.0590625 -0.05625   -0.0534375 -0.050625  -0.0478125
 -0.045     -0.0421875 -0.039375  -0.0365625 -0.03375   -0.0309375
 -0.028125  -0.0253125 -0.0225    -0.0196875 -0.016875  -0.0140625
 -0.01125   -0.0084375 -0.005625  -0.0028125  0.         0.0028125
  0.005625   0.0084375  0.01125    0.0140625  0.016875   0.0196875
  0.0225     0.0253125  0.028125   0.0309375  0.03375    0.0365625
  0.039375   0.0421875  0.045      0.0478125  0.050625   0.0534375
  0.05625    0.0590625  0.061875   0.0646875  0.0675     0.0703125
  0.073125   0.0759375  0.07875    0.0815625  0.084375   0.0871875
  0.09       0.0928125  0.095625   0.0984375  0.10125    0.1040625
  0.106875   0.1096875  0.1125     0.1153125  0.118125   0.1209375
  0.12375    0.1265625  0.129375   0.1321875  0.135      0.1378125
  0.140625   0.1434375  0.14625    0.1490625  0.151875   0.1546875
  0.1575     0.1603125  0.163125   0.1659375  0.16875    0.1715625
  0.174375   0.1771875]
{0.0225}
```
So 0.0225 is in the list, but set subtraction don't think they are the same.

Change data types of both `grid_left_edges[idx,iax]` and `cell_edges` to be `float32` seems work. But `float64` doesn't work somehow.

**Comment by neutrinoceros** [comment]
Thank you ! I was able to reproduce this.

> So 0.0225 is in the list, but set subtraction don't think they are the same.

Yes so I think that the list you showed above are rounded views on the numpy arrays, and when you convert to sets, you can see that the float in `cell_edges` is actually `0.022499999999999992`.

That's a floating point computations for you... I don't know how to address this correctly. @matthewturk , I know you've been scratching your head a lot with those, any advice ?

**Comment by matthewturk** [comment]
So I *think* the issue is a combination of yt being pretty zealous and the factor of three that shows up in the `0.18` values.  I see two options -- one which requires a code change, one which doesn't.

The first solution would be to scale your dataset on its way in.  Divide all of the lengths by 0.18 so that it runs from -1 to 1.  Then, when specifying `length_unit`, offset it by that factor -- so if it were "cm" before, it'd be "0.18 * cm" now.  If you're specifying units on your input fields, this may be the only place such an offset is necessary.

The other option would be to check for floating point *closesness*.  So instead of a set subtraction, do an NxM subtraction of the floating point values and check if any of them are within a few nulps.  That would be the better way, I think, but would require code modifications.

**Comment by neutrinoceros** [comment]
> That would be the better way, I think, but would require code modifications.

I'm willing to open a PR for this change, less work for the user is always preferable imo :)
I was hesitant to make the code any less strict, but I couldn't find a better way.
-

**Comment by caicairay** [comment]
Thank you both! The first solution sounds good for me. I will try.
