### ISSUE TITLE
REGRESSION: unyt fails to recognise "msun" symbol

### ISSUE THREAD

**Issue by neutrinoceros** [yt-project/yt#2704]
### Bug report

**Bug summary**

The following script loads correctly in yt 3.6, but fails on master

**Code for reproduction**
```python
import yt
my_units = {"mass_unit": (1.0, "msun")}
ds = yt.load("amrvac/bw_2d0000.dat", units_override=my_units)
```

since this has to do with switching from an internal module `yt.units` to `unyt` as a depedency, it seems a bit hard to track down with git bisect.
@ngoldbaum @jzuhone  @matthewturk , any thoughts ?

**Actual outcome**

```python
Traceback (most recent call last):
  File "btest.py", line 3, in <module>
    ds = yt.load("amrvac/bw_2d0000.dat", units_override=my_units)
  File "/Users/clm/dev/python/yt-project/yt/yt/convenience.py", line 80, in load
    return candidates[0](*args, **kwargs)
  File "/Users/clm/dev/python/yt-project/yt/yt/frontends/amrvac/data_structures.py", line 171, in __init__
    super(AMRVACDataset, self).__init__(filename, dataset_type,
  File "/Users/clm/dev/python/yt-project/yt/yt/data_objects/static_output.py", line 245, in __init__
    self.set_units()
  File "/Users/clm/dev/python/yt-project/yt/yt/data_objects/static_output.py", line 1024, in set_units
    self.set_code_units()
  File "/Users/clm/dev/python/yt-project/yt/yt/data_objects/static_output.py", line 1064, in set_code_units
    self._override_code_units()
  File "/Users/clm/dev/python/yt-project/yt/yt/frontends/amrvac/data_structures.py", line 404, in _override_code_units
    super(AMRVACDataset, self)._override_code_units()
  File "/Users/clm/dev/python/yt-project/yt/yt/data_objects/static_output.py", line 1117, in _override_code_units
    setattr(self, "%s_unit" % unit, self.quan(val[0], val[1]))
  File "/Users/clm/dev/python/yt-project/unyt/unyt/array.py", line 2030, in __new__
    ret = unyt_array.__new__(
  File "/Users/clm/dev/python/yt-project/unyt/unyt/array.py", line 548, in __new__
    units = Unit(input_units, registry=registry)
  File "/Users/clm/dev/python/yt-project/unyt/unyt/unit_object.py", line 265, in __new__
    unit_data = _get_unit_data_from_expr(unit_expr, registry.lut)
  File "/Users/clm/dev/python/yt-project/unyt/unyt/unit_object.py", line 968, in _get_unit_data_from_expr
    return _lookup_unit_symbol(unit_expr.name, unit_symbol_lut)
  File "/Users/clm/dev/python/yt-project/unyt/unyt/unit_registry.py", line 330, in _lookup_unit_symbol
    raise UnitParseError(
unyt.exceptions.UnitParseError: Could not find unit symbol 'msun' in the provided symbols.
```

**Expected outcome**

Either a correctly loaded dataset, or a deprecation warning (either from yt or unyt, I don't know) ?
I note that the same thing happen if I replace `"msun"` with `"mass_sun"` in both versions of yt.

**Version Information**
  * Python Version: 3.8
  * yt version: master branch (60fd5f31a)
  * Other Libraries (if applicable): unyt: master branch (de443df)

**Comment by Xarthisius** [comment]
It happened in https://github.com/yt-project/unyt/pull/65/commits/374175c7041d6217ec8b2fd0d89076d1eb7acfc3

**Comment by neutrinoceros** [comment]
Very nice ! thanks a bunch. Indeed it looks like "Msun" still parses correctly, so it shouldn't be hard to fix it there !
