### ISSUE TITLE
error in particle selection for clump objects

### ISSUE THREAD

**Issue by brittonsmith** [yt-project/yt#2841]
### Bug report

**Bug summary**

Running the ``find_clumps.py`` cookbook recipe and then calculating the total particle mass for each clump gives an error. The changes in PR #2836 fix a related issue when calculating total particle masses for just the leaf clumps, but it does not fix this issue.

**Code for reproduction**

Append the code below to the ``find_clumps.py`` cookbook recipe.

```python
for clump in master_clump:
    print (clump.quantities.total_mass())
```

**Actual outcome**

```
Traceback (most recent call last):
  File "find_clumps.py", line 42, in <module>
    leaf_masses = [leaf.quantities.total_mass() for leaf in leaf_clumps]
  File "find_clumps.py", line 42, in <listcomp>
    leaf_masses = [leaf.quantities.total_mass() for leaf in leaf_clumps]
  File "/Users/britton/Documents/work/research/yt/yt/yt/data_objects/derived_quantities.py", line 206, in __call__
    part = super(TotalMass, self).__call__([("nbody", "particle_mass")])
  File "/Users/britton/Documents/work/research/yt/yt/yt/data_objects/derived_quantities.py", line 170, in __call__
    rv = super(TotalQuantity, self).__call__(fields)
  File "/Users/britton/Documents/work/research/yt/yt/yt/data_objects/derived_quantities.py", line 56, in __call__
    sto.result = self.process_chunk(ds, *args, **kwargs)
  File "/Users/britton/Documents/work/research/yt/yt/yt/data_objects/derived_quantities.py", line 176, in process_chunk
    vals = [data[field].sum(dtype=np.float64) for field in fields]
  File "/Users/britton/Documents/work/research/yt/yt/yt/data_objects/derived_quantities.py", line 176, in <listcomp>
    vals = [data[field].sum(dtype=np.float64) for field in fields]
  File "/Users/britton/Documents/work/research/yt/yt/yt/data_objects/data_containers.py", line 265, in __getitem__
    self.get_data(f)
  File "/Users/britton/Documents/work/research/yt/yt/yt/data_objects/selection_data_containers.py", line 1099, in get_data
    self.field_data[field] = parent[field][self._part_ind(field[0])]
  File "/Users/britton/Documents/work/research/yt/yt/yt/data_objects/data_containers.py", line 265, in __getitem__
    self.get_data(f)
  File "/Users/britton/Documents/work/research/yt/yt/yt/data_objects/selection_data_containers.py", line 1099, in get_data
    self.field_data[field] = parent[field][self._part_ind(field[0])]
  File "/Users/britton/Documents/work/research/yt/yt/yt/data_objects/selection_data_containers.py", line 1221, in _part_ind
    return self._part_ind_KDTree(ptype)
  File "/Users/britton/Documents/work/research/yt/yt/yt/data_objects/selection_data_containers.py", line 1175, in _part_ind_KDTree
    dx_loc = dx[lvl_mask]
IndexError: boolean index did not match indexed array along dimension 0; dimension is 560 but corresponding boolean dimension is 8861
```

**Expected outcome**

The code should calculate the sum of all particle masses contained in each clump.

**Version Information**

  * Operating System: Mac OS 10.12.6
  * Python Version: 3.8.2
  * yt version: Changeset = 73121ae27d66
  * Other Libraries (if applicable): scipy 1.5.2 (required for kdtree)

I installed yt from source at the above changeset.

**Comment by brittonsmith** [comment]
@cphyc, do you have any thoughts on what the issue might be here?

**Comment by matthewturk** [comment]
I spent some time with @brittonsmith working on this today.  I was able to get it to run most of the way to completion with this diff:

```
diff --git a/yt/data_objects/selection_data_containers.py b/yt/data_objects/selection_data_containers.py
index 2c7fbc446..c0f9df36a 100644
--- a/yt/data_objects/selection_data_containers.py
+++ b/yt/data_objects/selection_data_containers.py
@@ -1082,15 +1082,16 @@ class YTCutRegion(YTSelectionContainer3D):
     def chunks(self, fields, chunking_style, **kwargs):
         # We actually want to chunk the sub-chunk, not ourselves.  We have no
         # chunks to speak of, as we do not data IO.
-        for chunk in self.index._chunk(self.base_object, chunking_style, **kwargs):
-            with self.base_object._chunked_read(chunk):
+        obj = getattr(self, "parent", self.base_object)
+        for chunk in self.index._chunk(obj, chunking_style, **kwargs):
+            with obj._chunked_read(chunk):
                 with self._chunked_read(chunk):
                     self.get_data(fields)
                     yield self
 
     def get_data(self, fields=None):
         fields = ensure_list(fields)
-        self.base_object.get_data(fields)
+        getattr(self, "parent", self.base_object).get_data(fields)
         ind = self._cond_ind
         for field in fields:
             f = self.base_object[field]
```

But I'm not 100% convinced this is the right thing.  It's also rather slow.  I think that might be because at all stages, it's doing the selection on the parent clump, maybe?

The next error I got is that `levels` is of zero size, but so is `dx` (in `_part_ind_KDTree`) so maybe that is just a situation where we want to continue.  Not sure why it's a clump with zero size, but.

Also I believe the issue is related to a mismatch in the chunking style mid-chunk iteration; changing the chunking style to `all` in `derived_quantities.py` also fixes it.

**Comment by cphyc** [comment]
So after #2836 is merged, would this issue still be relevant?

**Comment by brittonsmith** [comment]
We can close this now.
