### ISSUE TITLE
Error to display the output of cosmological simulations for Enzo

### ISSUE THREAD

**Issue by Jessica-Lopez** [yt-project/yt#3076]
Hello,

 I'm using yt to visualize the output of cosmological simulation by Enzo. Yt works with other examples, namely, noncosmological, but when I try to display a cosmological output using:

yt plot DD0000/DD0000

I got this error message

yt : [INFO     ] 2021-02-14 19:58:12,191 Parameters: current_time              = 0.81651006834053
yt : [INFO     ] 2021-02-14 19:58:12,191 Parameters: domain_dimensions         = [32 32 32]
yt : [INFO     ] 2021-02-14 19:58:12,192 Parameters: domain_left_edge          = [0. 0. 0.]
yt : [INFO     ] 2021-02-14 19:58:12,192 Parameters: domain_right_edge         = [1. 1. 1.]
yt : [INFO     ] 2021-02-14 19:58:12,192 Parameters: cosmological_simulation   = 1
yt : [INFO     ] 2021-02-14 19:58:12,192 Parameters: current_redshift          = 50
yt : [INFO     ] 2021-02-14 19:58:12,192 Parameters: omega_lambda              = 0.732
yt : [INFO     ] 2021-02-14 19:58:12,192 Parameters: omega_matter              = 0.268
yt : [INFO     ] 2021-02-14 19:58:12,192 Parameters: omega_radiation           = 0
yt : [INFO     ] 2021-02-14 19:58:12,192 Parameters: hubble_constant           = 0.704
yt : [INFO     ] 2021-02-14 19:58:12,193 Adding plot for axis 0
yt : [INFO     ] 2021-02-14 19:58:12,197 Gathering a field list (this may take a moment.)
Traceback (most recent call last):
  File "/home/jessica/anaconda3/bin/yt", line 11, in <module>
    sys.exit(run_main())
  File "/home/jessica/.local/lib/python3.8/site-packages/yt/utilities/command_line.py", line 1408, in run_main
    args.func(args)
  File "/home/jessica/.local/lib/python3.8/site-packages/yt/utilities/command_line.py", line 240, in run
    self(args)
  File "/home/jessica/.local/lib/python3.8/site-packages/yt/utilities/command_line.py", line 956, in __call__
    plt = SlicePlot(ds, ax, args.field, center=center,
  File "/home/jessica/.local/lib/python3.8/site-packages/yt/visualization/plot_window.py", line 1986, in SlicePlot
    return AxisAlignedSlicePlot(ds, normal, fields, *args, **kwargs)
  File "/home/jessica/.local/lib/python3.8/site-packages/yt/visualization/plot_window.py", line 1282, in __init__
    slc.get_data(fields)
  File "/home/jessica/.local/lib/python3.8/site-packages/yt/data_objects/data_containers.py", line 1511, in get_data
    for field in self._determine_fields(fields):
  File "/home/jessica/.local/lib/python3.8/site-packages/yt/data_objects/data_containers.py", line 1366, in _determine_fields
    finfo = self.ds._get_field_info("unknown", fname)
  File "/home/jessica/.local/lib/python3.8/site-packages/yt/data_objects/static_output.py", line 739, in _get_field_info
    raise YTFieldNotFound((ftype, fname), self)

  * Operating System: Ubuntu  20.04.2 LTS
  * Python Version: 3.8.5

yt was installed using 

 conda install -c conda-forge yt

**Comment by matthewturk** [comment]
Hi @Jessica-Lopez !  This might be a result of trying to plot `density` (which I think is the default) on a simulation that is DM-only.  Do you have gas fields in the data?

**Comment by Jessica-Lopez** [comment]
Thank you for your reply!

I'm using an example in enzo by default, but when I try to display all the fields (looking for gas field data), I got the same mistake also. 
I did a proof plotting a tiny cosmological simulation using the sample data in [https://yt-project.org/data/] and it works. 

Apparently what it's missing in my output directory are the hdf5 files. However when I try any other example in enzo (non cosmological, for instance) , all files including the hdf5 ones are generated I can plot the results with yt without any problem.

In addition, hdf5 in enzo is being taken from yt, path=/user/yt-conda/pkgs/hdf5-1.10.6-nompi_h7c3c948_1111
and now, yt was installed using bash install_script.sh

Is it possible that my issue is related to the hdf5 version i'm using?

**Comment by matthewturk** [comment]
It's *possible* but I think it might be something different.  Usually with
hdf5 issues, the error actually gets thrown and tells you that it's an HDF5
error.

One thing to check is to see what fields are available by loading it up in
python:

import yt
ds = yt.load("whatever")
ds.field_list
