### ISSUE TITLE
Segfault when using the 'radius' field with surfaces (RAMSES)

### ISSUE THREAD

**Issue by RicardaBeckmann** [yt-project/yt#3146]
### Bug report

**Bug summary**

When using the "radius" field, in conjunction with the surface object with RAMSES (OctTree based code), the kernel dies silently. It seems fine with other fluid fields such as density, temperature etc (not tested exhaustively but a quick look produced no issues except with the radius field)

**Code for reproduction**

```python
import yt
ds=yt.load('ramses_new_format/output_00002/info_00002.txt')
ad=ds.all_data()
surf=ad.surface('density',ds.quan(1E-27,'g/cm**3'))
surf['radius']
```

or alternatively 

```python
import yt
ds=yt.load('ramses_new_format/output_00002/info_00002.txt')
ad=ds.all_data()
surf=ad.surface('radius',ds.quan(2,'kpc'))
```

**Actual outcome**

Segfault in either case

```
In [10]: surf['radius']
yt : [INFO     ] 2021-03-25 17:22:41,723 Extracting (sampling: ('index', 'radius'))
Segmentation fault
```

**Version Information**

  * Operating System: Unix
  * Python Version: Python 3.8.8 
  * yt version: 4.0.dev0 (updated this morning, installed from source)

**Comment by cphyc** [comment]
I can reproduce locally, the stack trace obtained from gdb shows:
```
#0  0x00007fffb512cb60 in __pyx_f_2yt_8geometry_13oct_container_root_node_compare ()
   from /home/XXX/Documents/prog/yt/yt/geometry/oct_container.cpython-39-x86_64-linux-gnu.so
#1  0x00007ffff7e9723b in tfind () from /usr/lib/libc.so.6
#2  0x00007fffb512db1d in __pyx_f_2yt_8geometry_13oct_container_21SparseOctreeContainer_get_root ()
   from /home/XXX/Documents/prog/yt/yt/geometry/oct_container.cpython-39-x86_64-linux-gnu.so
#3  0x00007fffb512dcc5 in __pyx_f_2yt_8geometry_13oct_container_15OctreeContainer_get ()
   from /home/XXX/Documents/prog/yt/yt/geometry/oct_container.cpython-39-x86_64-linux-gnu.so
#4  0x00007fffb52a1527 in __pyx_f_2yt_8geometry_12oct_visitors_20BaseNeighbourVisitor_set_neighbour_info ()
   from /home/XXX/Documents/prog/yt/yt/geometry/oct_visitors.cpython-39-x86_64-linux-gnu.so
#5  0x00007fffb529193b in __pyx_f_2yt_8geometry_12oct_visitors_25NeighbourCellIndexVisitor_visit ()
   from /home/XXX/Documents/prog/yt/yt/geometry/oct_visitors.cpython-39-x86_64-linux-gnu.so
#6  0x00007fffb51fcf2d in __pyx_f_2yt_8geometry_18selection_routines_14SelectorObject_recursively_visit_octs ()
   from /home/XXX/Documents/prog/yt/yt/geometry/selection_routines.cpython-39-x86_64-linux-gnu.so
#7  0x00007fffb512cd41 in __pyx_f_2yt_8geometry_13oct_container_21SparseOctreeContainer_visit_all_octs ()
   from /home/XXX/Documents/prog/yt/yt/geometry/oct_container.cpython-39-x86_64-linux-gnu.so
#8  0x00007fffb5166f2b in __pyx_pf_2yt_8geometry_13oct_container_15OctreeContainer_42fill_octcellindex_neighbours ()
   from /home/XXX/Documents/prog/yt/yt/geometry/oct_container.cpython-39-x86_64-linux-gnu.so
[...]
``
