### ISSUE TITLE
set_background_color no longer works for cmocean colormaps

### ISSUE THREAD

**Issue by chummels** [yt-project/yt#3208]
### Bug report

**Bug summary**

Something about the changes in PR #3175 seems to have broken `set_background_color` when using cmocean colormaps.  

**Code for reproduction**

This script used to work:

```
import yt

ds = yt.testing.fake_amr_ds()
p = yt.SlicePlot(ds, "z", 'Density')
p.set_cmap('all', "balance")
p.set_background_color('Density')
```

After applying the changes described in PR #3175 and now documented in PR #3207, this script show now look like this:

```
import yt
import cmocean

ds = yt.testing.fake_amr_ds()
p = yt.SlicePlot(ds, "z", 'Density')
p.set_cmap('all', "cmo.balance")
p.set_background_color('Density')
```

But it fails with this error:

```
Traceback (most recent call last):
  File "/Users/chummels/src/yt/yt/visualization/plot_container.py", line 896, in set_background_color
    cmap = yt_colormaps[cmap]
KeyError: 'cmo.balance'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "cmo_test.py", line 7, in <module>
    p.set_background_color('Density')
  File "/Users/chummels/src/yt/yt/visualization/plot_container.py", line 105, in newfunc
    func(self, f, *args, **kwargs)
  File "/Users/chummels/src/yt/yt/visualization/plot_container.py", line 56, in newfunc
    rv = f(*args, **kwargs)
  File "/Users/chummels/src/yt/yt/visualization/plot_container.py", line 898, in set_background_color
    cmap = getattr(matplotlib.cm, cmap)
AttributeError: module 'matplotlib.cm' has no attribute 'cmo.balance'
```

**Comment by neutrinoceros** [comment]
Weird... the good news is that the traceback correctly points to the exact line that's buggy. I'll try to fix this later today, thank you so much for reporting !
