### ISSUE TITLE
Issue in `load_sample` when loading MHDSloshing

### ISSUE THREAD

**Issue by cphyc** [yt-project/yt#3322]
### Bug report

**Bug summary**

A TypeError is raised when trying to `load_sample` the MHDSloshing dataset.

**Code for reproduction**

```python
import yt                         
yt.load_sample("MHDSloshing")
```
Traceback:
```                                 
Traceback (most recent call last):
  File "<string>", line 2, in <module>
  File "/home/ccc/Documents/prog/yt/yt/loaders.py", line 1337, in load_sample
    return load(loadable_path, **kwargs)
  File "/home/ccc/Documents/prog/yt/yt/loaders.py", line 91, in load
    return candidates[0](fn, *args, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'length_unit'
```

**Comment by neutrinoceros** [comment]
incomplete duplicate to #3323 (likely a hiccup on GH, these were posted while services were running in degraded mode)
