### ISSUE TITLE
Issue in `load_sample` when loading MHDSloshing

### ISSUE THREAD

**Issue by cphyc** [yt-project/yt#3323]
### Bug report

**Bug summary**

A TypeError is raised when trying to `load_sample` the MHDSloshing dataset.

**Code for reproduction**

```python
import yt                         
yt.load_sample("MHDSloshing")
```
Traceback:
```                                 
Traceback (most recent call last):
  File "<string>", line 2, in <module>
  File "/home/ccc/Documents/prog/yt/yt/loaders.py", line 1337, in load_sample
    return load(loadable_path, **kwargs)
  File "/home/ccc/Documents/prog/yt/yt/loaders.py", line 91, in load
    return candidates[0](fn, *args, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'length_unit'
```

A possible solution is to apply the following diff:
```diff
diff --git a/yt/sample_data_registry.json b/yt/sample_data_registry.json
index b1c169dd9..431e08034 100644
--- a/yt/sample_data_registry.json
+++ b/yt/sample_data_registry.json
@@ -280,18 +280,20 @@
   "MHDSloshing.tar.gz": {
     "hash": "f0d0b4e26145a2f7445c3afed8ed0294026a2209496c477cc0d1a7a0f022bf38",
     "load_kwargs": {
-      "length_unit": [
-        1.0,
-        "Mpc"
-      ],
-      "mass_unit": [
-        100000000000000.0,
-        "Msun"
-      ],
-      "time_unit": [
-        1.0,
-        "Myr"
-      ]
+      "units_override": {
+        "length_unit": [
+          1.0,
+          "Mpc"
+        ],
+        "mass_unit": [
+          100000000000000.0,
+          "Msun"
+        ],
+        "time_unit": [
+          1.0,
+          "Myr"
+        ]
+      }
     },
     "load_name": "virgo_low_res.0054.vtk",
     "url": "https://yt-project.org/data/MHDSloshing.tar.gz"
```

**Comment by jzuhone** [comment]
This is in fact the correct way to do it

**Comment by neutrinoceros** [comment]
There is exactly one other dataset that fails to load for the same reason (and hopefully would be fixed the same way): "RamPressureStripping"
