### ISSUE TITLE
Bounding box is not verified in cached ParticleBitmap index

### ISSUE THREAD

**Issue by Xarthisius** [yt-project/yt#3327]
### Bug report

Existing ewah file is always used, regardless if `bounding_box` used to load dataset matches the previous value.

**Bug summary**

**Code for reproduction**

```python
from yt.utilities.answer_testing.framework import data_dir_load

def access_some_data(ds):
    field = ("gas", "temperature")
    weight_field = ("gas", "density")
    axis = 0
    obj = ds.sphere("c", (0.1, "unitary"))
    proj = ds.proj(field, axis, weight_field=weight_field, data_source=obj)
    frb = proj.to_frb((1.0, "unitary"), 256)
    frb[field]

tng59_h5 = "TNGHalo/halo_59.hdf5"
_tng59_bbox = [[45135.0, 51343.0], [51844.0, 56184.0], [60555.0, 63451.0]]

# Load for the first time with bbox to dump an ewah file
ds = data_dir_load(tng59_h5)
access_some_data(ds)

ds = data_dir_load(tng59_h5, kwargs={"bounding_box": _tng59_bbox})
access_some_data(ds)
```

**Actual outcome**

```
Traceback (most recent call last):
  File "/home/xarth/codes/xarthisius/yt/yt/visualization/fixed_resolution.py", line 159, in __getitem__
    units = self.data_source._projected_units[it]
KeyError: ('gas', 'temperature')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/xarth/codes/xarthisius/yt/yt/data_objects/data_containers.py", line 264, in __getitem__
    rv = self.field_data[f]
KeyError: ('gas', 'temperature')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "bug.py", line 17, in <module>
    access_some_data(ds)
  File "bug.py", line 10, in access_some_data
    frb[field]
  File "/home/xarth/codes/xarthisius/yt/yt/visualization/fixed_resolution.py", line 161, in __getitem__
    units = self.data_source[item].units
  File "/home/xarth/codes/xarthisius/yt/yt/data_objects/data_containers.py", line 270, in __getitem__
    rv = self.ds.arr(self.field_data[key], fi.units)
KeyError: ('gas', 'temperature')
```

**Expected outcome**

No angry traceback.

**Version Information**
  * Operating System: Ubuntu 18.04
  * Python Version: 3.8
  * yt version: 63bb72ae8ae9d27bd179997925e4135979bcfa7f

**Comment by jzuhone** [comment]
Is this bug fixed by PR #3326?

**Comment by Xarthisius** [comment]
Nope, it's still present in `main`.

**Comment by matthewturk** [comment]
The way we store EWAH is a bit fragile at the moment.  This should not be fixed for this bug, but we should move to a key/value store or something that lets us query what is available and use that, and it could include the boundingbox.

**Comment by jzuhone** [comment]
@Xarthisius I get failures even when I don't use the bounding_box:

```python
from yt.utilities.answer_testing.framework import data_dir_load

def access_some_data(ds):
    field = ("gas", "temperature")
    weight_field = ("gas", "density")
    axis = 0
    obj = ds.sphere("c", (0.1, "unitary"))
    proj = ds.proj(field, axis, weight_field=weight_field, data_source=obj)
    frb = proj.to_frb((1.0, "unitary"), 256)
    frb[field]

tng59_h5 = "TNGHalo/halo_59.hdf5"
#_tng59_bbox = [[45135.0, 51343.0], [51844.0, 56184.0], [60555.0, 63451.0]]

# Load for the first time with bbox to dump an ewah file
ds = data_dir_load(tng59_h5)
access_some_data(ds)
```

```pytraceback
KeyError                                  Traceback (most recent call last)
File ~/Source/yt/yt/visualization/fixed_resolution.py:186, in FixedResolutionBuffer.__getitem__(self, item)
    185         it = item
--> 186     units = self.data_source._projected_units[it]
    187 except (KeyError, AttributeError):

KeyError: ('gas', 'temperature')

During handling of the above exception, another exception occurred:

KeyError                                  Traceback (most recent call last)
File ~/Source/yt/yt/data_objects/data_containers.py:268, in YTDataContainer.__getitem__(self, key)
    267 try:
--> 268     rv = self.field_data[f]
    269 except KeyError:

KeyError: ('gas', 'temperature')

During handling of the above exception, another exception occurred:

KeyError                                  Traceback (most recent call last)
/Users/jzuhone/Source/proposals/nsf2020/fix_ewah.ipynb Cell 1 in <cell line: 18>()
     [14](vscode-notebook-cell:/Users/jzuhone/Source/proposals/nsf2020/fix_ewah.ipynb#ch0000000?line=13) #_tng59_bbox = [[45135.0, 51343.0], [51844.0, 56184.0], [60555.0, 63451.0]]
     [15](vscode-notebook-cell:/Users/jzuhone/Source/proposals/nsf2020/fix_ewah.ipynb#ch0000000?line=14) 
...
    273         fi = self.ds._get_field_info("unknown", f)
--> 274     rv = self.ds.arr(self.field_data[key], fi.units)
    275 return rv

KeyError: ('gas', 'temperature')
```

**Comment by jzuhone** [comment]
it's because there's no data within the sphere selected (separate bug that needs fixing, should return an empty image)

**Comment by neutrinoceros** [comment]
@jzuhone should we close this ?

**Comment by jzuhone** [comment]
@neutrinoceros not yet
