### ISSUE TITLE
Initializing simulation from outside directory

### ISSUE THREAD

**Issue by SamJPatrick** [yt-project/yt#3464]
### Bug report

**Bug summary**

The module is unable to load simulations from outside the simulation directory when path is passed as an argument the 'load_simulation()' method. When attempting to subsequently load the data with 'get_time_series()' the code returns a null object instead of a list of directories

**Code for reproduction**

import yt
sim = yt.load_simulation("path/to/sim/directory/DD00xx/DD00xx", 'Enzo')
sim.get_time_series()
first = sim[0]

**Actual outcome**

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/anaconda/3.7/pkgs/yt/yt/data_objects/time_series.py", line 220, in __getitem__
    o = self._pre_outputs[key]
IndexError: list index out of range

**Expected outcome**

DD00xx/D00xx

**Version Information**

  * Operating System: Linux
  * Python Version: 3.7.10
  * yt version: 4.0.dev0
  * Other Libraries (if applicable): 

Yt installed via Anaconda, compiled with GCC 7.3.0

**Comment by neutrinoceros** [comment]
Hi, this looks like a bug indeed but I'm not sure `yt.load_simulation` is actually needed to do what you want here.
Would this work instead ?
```python
sim = yt.load_simulation("path/to/sim/directory/DD????/DD????", 'Enzo')
```

**Comment by neutrinoceros** [comment]
sorry my first comment wasn't working as intended, fixed it.
