### ISSUE TITLE
OffAxisProjectionPlot Failed when Log Level Set to Debug

### ISSUE THREAD

**Issue by cindytsai** [yt-project/yt#3568]
### Bug report

**Bug summary**
If log level set to `debug`, then `OffAxisProjectionPlot` would fail when following the tutorial at [website](https://yt-project.org/doc/visualizing/plots.html#off-axis-projection-plots). 
Alhough this can be avoid by setting log level to `info`, it is kind of annoying when debugging.

**Code for reproduction**

```python
import yt

ds = yt.load("IsolatedGalaxy/galaxy0030/galaxy0030")
L = [1, 1, 0]  # vector normal to cutting plane
north_vector = [-1, 1, 0]
prj = yt.OffAxisProjectionPlot(
    ds, L, ("gas", "density"), width=(25, "kpc"), north_vector=north_vector
)
prj.save()
```

**Actual outcome**

```
yt : [DEBUG    ] 2021-10-15 13:54:47,845 Setting normalized vectors [-0.5 -0.5 -0.5] dimensionless None
Traceback (most recent call last):
  File "OffAxisProjectionPlot.py", line 6, in <module>
    prj = yt.OffAxisProjectionPlot(
  File "/home/calab912/software/python/python3.8/lib/python3.8/site-packages/yt/visualization/plot_window.py", line 2254, in __init__
    PWViewerMPL.__init__(
  File "/home/calab912/software/python/python3.8/lib/python3.8/site-packages/yt/visualization/plot_window.py", line 873, in __init__
    PlotWindow.__init__(self, *args, **kwargs)
  File "/home/calab912/software/python/python3.8/lib/python3.8/site-packages/yt/visualization/plot_window.py", line 257, in __init__
    self._setup_plots()
  File "/home/calab912/software/python/python3.8/lib/python3.8/site-packages/yt/visualization/plot_window.py", line 994, in _setup_plots
    self._recreate_frb()
  File "/home/calab912/software/python/python3.8/lib/python3.8/site-packages/yt/visualization/plot_window.py", line 317, in _recreate_frb
    self._frb._get_data_source_fields()
  File "/home/calab912/software/python/python3.8/lib/python3.8/site-packages/yt/visualization/fixed_resolution.py", line 176, in _get_data_source_fields
    self[f]
  File "/home/calab912/software/python/python3.8/lib/python3.8/site-packages/yt/visualization/fixed_resolution.py", line 602, in __getitem__
    buff = off_axis_projection(
  File "/home/calab912/software/python/python3.8/lib/python3.8/site-packages/yt/visualization/volume_rendering/off_axis_projection.py", line 341, in off_axis_projection
    camera.set_width(width)
  File "/home/calab912/software/python/python3.8/lib/python3.8/site-packages/yt/visualization/volume_rendering/camera.py", line 374, in set_width
    self.width = width
  File "/home/calab912/software/python/python3.8/lib/python3.8/site-packages/yt/visualization/volume_rendering/camera.py", line 208, in fset
    self.switch_orientation()
  File "/home/calab912/software/python/python3.8/lib/python3.8/site-packages/yt/visualization/volume_rendering/camera.py", line 441, in switch_orientation
    self._setup_normalized_vectors(normal_vector, north_vector)
  File "/home/calab912/software/python/python3.8/lib/python3.8/site-packages/yt/utilities/orientation.py", line 65, in _setup_normalized_vectors
    mylog.debug("Setting normalized vectors %s %s", normal_vector, north_vector)
  File "/home/calab912/software/python/python3.8/lib/python3.8/logging/__init__.py", line 1422, in debug
    self._log(DEBUG, msg, args, **kwargs)
  File "/home/calab912/software/python/python3.8/lib/python3.8/logging/__init__.py", line 1577, in _log
    self.handle(record)
  File "/home/calab912/software/python/python3.8/lib/python3.8/logging/__init__.py", line 1586, in handle
    if (not self.disabled) and self.filter(record):
  File "/home/calab912/software/python/python3.8/lib/python3.8/logging/__init__.py", line 807, in filter
    result = f.filter(record)
  File "/home/calab912/software/python/python3.8/lib/python3.8/site-packages/yt/utilities/logger.py", line 78, in filter
    if current_log != getattr(self, "last_log", None):
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
```

**Expected outcome**

![8270b9edbcab48d09023e31ed0967ea6galaxy0030_OffAxisProjection_density](https://user-images.githubusercontent.com/6188366/137440172-7e9bde2e-4a04-459b-b05a-8c41ef0d45e3.png)

**Version Information**
  * Operating System: Ubuntu 20.04
  * Python Version: 3.8
  * yt version: 4.1.dev `yt/main` commit `e387a2`
  * Install from source code via pip.

**Comment by cindytsai** [comment]
> Hi @cindytsai, thank you for reporting this! This looks a lot like #3547, I'll issue a fix. Please keep it coming if you see more of this stuff, we really appreciate bug reports :)

Ok!
