### ISSUE TITLE
BUG: image tests on Jenkins are unstable

### ISSUE THREAD

**Issue by neutrinoceros** [yt-project/yt#3690]
### Bug report

**Bug summary**

We're getting 237 errors in image tests on Jenkins, consistently on several unrelated PRs:
see queue https://tests.yt-project.org/job/yt_py38_git/

I do not understand what's happening or what might have caused this, internally or externally.

**Comment by neutrinoceros** [comment]
maybe unrelated but I see some weird issues in the doc build too https://tests.yt-project.org/job/yt_docs_new/

**Comment by Xarthisius** [comment]
> maybe unrelated but I see some weird issues in the doc build too https://tests.yt-project.org/job/yt_docs_new/

Why
```
Traceback (most recent call last):
  File "/var/jenkins_home/workspace/yt_docs_new/yt/visualization/plot_window.py", line 1391, in run_callbacks
    callback(cbw)
  File "/var/jenkins_home/workspace/yt_docs_new/yt/visualization/plot_modifications.py", line 39, in _check_geometry
    supp = self._supported_geometries
AttributeError: 'TitleCallback' object has no attribute '_supported_geometries'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/var/jenkins_home/workspace/yt_docs_new/doc/source/visualizing/colormaps/cmap_images.py", line 16, in <module>
    p.save(f"Projection_{cmap.replace(' ', '_')}.png")
  File "/var/jenkins_home/workspace/yt_docs_new/yt/visualization/plot_container.py", line 78, in newfunc
    args[0]._setup_plots()
  File "/var/jenkins_home/workspace/yt_docs_new/yt/visualization/plot_window.py", line 1279, in _setup_plots
    self.run_callbacks()
  File "/var/jenkins_home/workspace/yt_docs_new/yt/visualization/plot_window.py", line 1395, in run_callbacks
    raise YTPlotCallbackError(callback._type_name) from e
yt.utilities.exceptions.YTPlotCallbackError: annotate_title callback failed
```
AttributeError is a weird issue?

**Comment by neutrinoceros** [comment]
This particular one is, because `TitleCallback` inherits from `PlotCallback`, which has a class-level default for `_supported_geometries`, so I have no idea how it's possible that we end up with 
```
AttributeError: 'TitleCallback' object has no attribute '_supported_geometries'
```

**Comment by neutrinoceros** [comment]
in fact this error is easy to reproduce locally (annotate_title is broken on main), so I'll patch this

**Comment by neutrinoceros** [comment]
Looks stable again. @Xarthisius, should we close this ?

**Comment by matthewturk** [comment]
Yup.
