### ISSUE TITLE
Test failures with numpy==1.22.0

### ISSUE THREAD

**Issue by Xarthisius** [yt-project/yt#3742]
### Bug report

**Bug summary**

New version of numpy was released on 12/31/21 and it's causing havoc in test suite, e.g.:

```
Traceback (most recent call last):
  File "/home/fido/shiningpanda/jobs/a7d58705/virtualenvs/d41d8cd9/lib/python3.8/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/home/fido/workspace/yt_py38_git/yt/utilities/answer_testing/framework.py", line 398, in __call__
    self.compare(nv, ov)
  File "/home/fido/workspace/yt_py38_git/yt/utilities/answer_testing/framework.py", line 1067, in compare
    compare_image_lists(new_result, old_result, self.decimals)
  File "/home/fido/workspace/yt_py38_git/yt/utilities/answer_testing/framework.py", line 816, in compare_image_lists
    expected = np.loads(zlib.decompress(old_result[i]))
  File "/home/fido/shiningpanda/jobs/a7d58705/virtualenvs/d41d8cd9/lib/python3.8/site-packages/numpy/__init__.py", line 315, in __getattr__
    raise AttributeError("module {!r} has no attribute "
AttributeError: module 'numpy' has no attribute 'loads'
```

There might be more.

**Comment by neutrinoceros** [comment]
getting some 
```
RuntimeWarning: numpy.ndarray size changed, may indicate binary incompatibility. Expected 88 from C header, got 96 from PyObject
```
in jobs launched in the last hour. Plausibly related.

**Comment by Xarthisius** [comment]
> getting some
> 
> ```
> RuntimeWarning: numpy.ndarray size changed, may indicate binary incompatibility. Expected 88 from C header, got 96 from PyObject
> ```
> 
> in jobs launched in the last hour. Plausibly related.

Yeah, note it's not even us. I'm seeing that in astropy.

**Comment by neutrinoceros** [comment]
> Yeah, note it's not even us. I'm seeing that in astropy.

yup, I second that.
Weird how often astropy keeps growing incompatibilities with NumPy even though they started `oldest-supported-numpy`

**Comment by neutrinoceros** [comment]
`np.loads()` was effectively deprecated a while back and removed in numpy 1.22, I don't understand how we've missed this.

https://numpy.org/doc/stable/release/1.22.0-notes.html#expired-deprecations-for-loads-ndfromtxt-and-mafromtxt-in-npyio
