### ISSUE TITLE
yt no longer supports empty particle datasets

### ISSUE THREAD

**Issue by brittonsmith** [yt-project/yt#3825]
### Bug report

yt no longer handles empty particle datasets cleanly. An example of this would be a halo catalog with no halos. These can still be loaded, but failure occurs later in poorly defined ways.
Sample data: [here](http://use.yt/upload/02ce88fe)

This can be reproduced by doing:
```python
import yt
ds = yt.load("rockstar_halos/halos_DD0000.0.bin")
ad = ds.all_data()
```

which gives:
```
yt : [INFO     ] 2022-02-23 13:03:51,109 Allocating for 0.000e+00 particles
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/brs/stack/yt/yt/data_objects/static_output.py", line 1044, in all_data
    self.index
  File "/home/brs/stack/yt/yt/data_objects/static_output.py", line 531, in index
    self._instantiated_index = self._index_class(
  File "/home/brs/stack/yt/yt/geometry/particle_geometry_handler.py", line 27, in __init__
    self._initialize_index()
  File "/home/brs/stack/yt/yt/geometry/particle_geometry_handler.py", line 157, in _initialize_index
    self.regions = ParticleBitmap(
  File "yt/geometry/particle_oct_container.pyx", line 476, in yt.geometry.particle_oct_container.ParticleBitmap.__init__
TypeError: an integer is required
```

What's happening here is that  `Dataset._file_hash` is set to `None` by `ParticleIndex._generate_hash`. This happens because the dataset has no actual data files, since only data files with non-zero numbers of particles are included in the geometry handler. This `None` is passed to the `ParticleBitmap` instantiation and we crash.

Changing the file has to, e.g. `0`, gets things further along, but there is another error based on the assumption that the data file list is not empty. Prior to yt-4.0, data containers could be created for empty datasets and field query would simply return empty arrays. I think this behavior either needs to be restored or a more informative exception should be raised that the user can properly deal with.

**Comment by neutrinoceros** [comment]
I made a lazy attempt at bisecting this regression and I could not load the dataset with yt 3.6.1 either.

**Comment by brittonsmith** [comment]
I'm surprised by that. I could have sworn this worked at some point. I only noticed this because an old script of mine no longer works. In any case, I do think it's worth making it so things at least fail a little more gracefully than they do now. I'm happy to look into this myself.

**Comment by neutrinoceros** [comment]
> In any case, I do think it's worth making it so things at least fail a little more gracefully than they do now.

Agreed

**Comment by neutrinoceros** [comment]
btw I couldn't help but notice that the logged message is kinda poorly formatted when there are less than 1000 particles

```
yt : [INFO     ] 2022-02-23 13:03:51,109 Allocating for 0.000e+00 particles
```

this patch fixes it
```patch
diff --git a/yt/geometry/particle_geometry_handler.py b/yt/geometry/particle_geometry_handler.py
index 5fecbd5de..af0450b2f 100644
--- a/yt/geometry/particle_geometry_handler.py
+++ b/yt/geometry/particle_geometry_handler.py
@@ -103,7 +103,7 @@ class ParticleIndex(Index):
         ds = self.dataset
         only_on_root(
             mylog.info,
-            "Allocating for %0.3e particles",
+            "Allocating for %0.3g particles",
             self.total_particles,
             global_rootonly=True,
         )
```
into
```
yt : [INFO     ] 2022-02-25 11:45:53,715 Allocating for 0 particles
```
Feel free to incorporate it to your upcoming PR @brittonsmith
