### ISSUE TITLE
BUG: Selecting the domain's right edge doesn't work

### ISSUE THREAD

**Issue by neutrinoceros** [yt-project/yt#3828]
### Bug report

**Bug summary**
This simple script demonstrates that making a SlicePlot exactly on the left edge works, but not on the right edge.
I assume this is reminiscent of a bias somewhere in selection routines, but right now I don't have a clear idea where that would be.
I'm hopeful that fixing this could be a simple matter of changing a `>` into a `>=` or something similar, the challenge lies in finding where.

**Code for reproduction**

```python
import yt
from yt.testing import fake_amr_ds

ds = fake_amr_ds(fields=[("gas", "density")], units=["g/cm**3"])

axis = 2
left = ds.domain_center.copy()
left[axis] = ds.domain_left_edge[axis]
right = ds.domain_center.copy()
right[axis] = ds.domain_right_edge[axis]

for name, center in (("left", left), ("right", right)):
    p = yt.SlicePlot(ds, axis, "density", center=center)
    p.save(f"/tmp/center_{name}.png")
```

**Actual outcome**
left edge ✅ 
![center_left](https://user-images.githubusercontent.com/14075922/156006479-7cfc0b95-b36b-4ff9-a0a3-e589c8abb829.png)

right edge ❌
![center_right](https://user-images.githubusercontent.com/14075922/156006515-2d7d6da3-2215-400b-94d1-1fb76736dc67.png)

For other classes of datasets, this can fail in a much worse fashion, for instance using `ds = yt.load_sample("IsolatedGalaxy")`, we get a crash

<details> <summary> Traceback </summary>

```python-traceback
Traceback (most recent call last):
  File "t_center.py", line 16, in <module>
    p = yt.SlicePlot(ds, axis, "density", center=center)
  File "/Users/robcleme/dev/yt-project/yt/yt/visualization/plot_window.py", line 1972, in __init__
    slc.get_data(fields)
  File "/Users/robcleme/dev/yt-project/yt/yt/data_objects/selection_objects/data_selection_objects.py", line 196, in get_data
    read_fluids, gen_fluids = self.index._read_fluid_fields(
  File "/Users/robcleme/dev/yt-project/yt/yt/geometry/geometry_handler.py", line 226, in _read_fluid_fields
    fields_to_return = self.io._read_fluid_selection(
  File "/Users/robcleme/dev/yt-project/yt/yt/utilities/io_handler.py", line 128, in _read_fluid_selection
    for field, obj, data in self.io_iter(chunks, fields):
  File "/Users/robcleme/dev/yt-project/yt/yt/frontends/enzo/io.py", line 149, in io_iter
    if fid is not None:
UnboundLocalError: local variable 'fid' referenced before assignment
```
</details>

**Comment by neutrinoceros** [comment]
I note that both datasets used to illustrate this issue are periodic in all directions. I figure it should be possible to perform this selection at the very least for this kind of data.

**Comment by neutrinoceros** [comment]
So after a failed attempt at fixing this at the level of selection routines, I believe this is near-impossible to fix.
*However* there's a viable workaround from the user standpoint, which consists in deliberately shifting the center ever so slightly away from the right edge, like so
```python
import numpy as np
import yt
from yt.testing import fake_amr_ds

ds = fake_amr_ds(fields=[("gas", "density")], units=["g/cm**3"])

axis = 2
right = ds.domain_center.copy()
right[axis] = ds.domain_right_edge[axis] * (1.0 - np.finfo(np.float64).eps)

p = yt.SlicePlot(ds, axis, "density", center=right)
p.save(f"/tmp/center_right.png")
```
![center_right](https://user-images.githubusercontent.com/14075922/156191446-c269e9f1-3fe4-4284-9e77-faecefb3254c.png)

Now I don't think the issue is actionable or worth keeping open, so let's just close it.
