### ISSUE TITLE
BUG: cannot plot data containing both finite and infinite values and use set_zlim

### ISSUE THREAD

**Issue by neutrinoceros** [yt-project/yt#3901]
### Bug report

**Bug summary**
I wish I could say this never happens in production, but then again...

**Code for reproduction**

```python
import yt
import numpy as np

shape = (32, 16, 1)
a = np.ones(16)
b = np.ones((32, 16))
c = np.reshape(a*b, shape)

# injecting ONE inf value
c[0, 0, 0] = np.inf

data = {("gas", "density"): c}

ds = yt.load_uniform_grid(
    data,
    shape,
    bbox=np.array([[0,1],[0,1],[0,1]]),
)
p = yt.SlicePlot(ds,"z",("gas", "density"))

# setting zlim manually
p.set_zlim(("gas", "density"), -10, 10)
p.save("/tmp/test.png")
```

**Actual outcome**

```
Traceback (most recent call last):
  File "/Users/robcleme/dev/yt-project/yt/inf_symlog.py", line 19, in <module>
    p.save("/tmp/test.png")
  File "/Users/robcleme/dev/yt-project/yt/yt/visualization/plot_container.py", line 78, in newfunc
    args[0]._setup_plots()
  File "/Users/robcleme/dev/yt-project/yt/yt/visualization/plot_window.py", line 1134, in _setup_plots
    self.plots[f] = WindowPlotMPL(
  File "/Users/robcleme/dev/yt-project/yt/yt/visualization/plot_window.py", line 2640, in __init__
    self._init_image(data, cbname, cblinthresh, cmap, extent, aspect)
  File "/Users/robcleme/dev/yt-project/yt/yt/visualization/base_plot_types.py", line 360, in _init_image
    self.cb = self.figure.colorbar(self.image, self.cax)
  File "/Users/robcleme/.pyenv/versions/yt-dev/lib/python3.10/site-packages/matplotlib/figure.py", line 1158, in colorbar
    cb = cbar.Colorbar(cax, mappable, **cb_kw)
  File "/Users/robcleme/.pyenv/versions/yt-dev/lib/python3.10/site-packages/matplotlib/colorbar.py", line 484, in __init__
    self._reset_locator_formatter_scale()
  File "/Users/robcleme/.pyenv/versions/yt-dev/lib/python3.10/site-packages/matplotlib/colorbar.py", line 1175, in _reset_locator_formatter_scale
    self._process_values()
  File "/Users/robcleme/.pyenv/versions/yt-dev/lib/python3.10/site-packages/matplotlib/colorbar.py", line 1117, in _process_values
    b = self.norm.inverse(b)
  File "/Users/robcleme/.pyenv/versions/yt-dev/lib/python3.10/site-packages/matplotlib/colors.py", line 1554, in inverse
    raise ValueError("Invalid vmin or vmax")
ValueError: Invalid vmin or vmax
```

**Expected outcome**
The image should be handled correctly and only the one `inf` cell should be masked.

This currently doesn't work (and has never worked, at least since yt 4.0.0) because the only line of defense against inifinite values we have at the moment is:
https://github.com/yt-project/yt/blob/41c82596730500eb31747d12d935de361aab3035/yt/visualization/plot_window.py#L1065

So yt behaves correctly when the data has *only* infinite values but breaks when there are also finite ones.

**Comment by neutrinoceros** [comment]
I don't think there's a easy fix for this within the current state of the code, but it's actually trivial with #3849, so there's that.
