### ISSUE TITLE
TST: failed answers reporting is broken ?

### ISSUE THREAD

**Issue by neutrinoceros** [yt-project/yt#3910]
### Bug report

**Bug summary**
Lately, it seems that the answer tests job on GHA is broken as the reporting stage is not working
This is the kind of errors that keeps popping

```
[152](https://github.com/yt-project/yt/runs/6149317276?check_suite_focus=true#step:7:152)
Traceback (most recent call last):
[153](https://github.com/yt-project/yt/runs/6149317276?check_suite_focus=true#step:7:153)
  File "tests/report_failed_answers.py", line 428, in <module>
[154](https://github.com/yt-project/yt/runs/6149317276?check_suite_focus=true#step:7:154)
    if response.ok:
[155](https://github.com/yt-project/yt/runs/6149317276?check_suite_focus=true#step:7:155)
AttributeError: 'NoneType' object has no attribute 'ok'
[156](https://github.com/yt-project/yt/runs/6149317276?check_suite_focus=true#step:7:156)
Error: Process completed with exit code 1.
```
see for instance the following failed job https://github.com/yt-project/yt/runs/6270503422?check_suite_focus=true

It looks to me that this may be a server side issue.

**Comment by neutrinoceros** [comment]
@Xarthisius any chance you could have a look ?

**Comment by Xarthisius** [comment]
For GHA tests your guess is as good as mine.

**Comment by Xarthisius** [comment]
I would start with fixing:
```
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/home/runner/work/yt/yt/yt/utilities/answer_testing/framework.py", line 362, in __call__
    nv = self.run()
  File "/home/runner/work/yt/yt/yt/utilities/answer_testing/framework.py", line 977, in run
    plot.save(name=tmpname)
  File "/home/runner/work/yt/yt/yt/visualization/_commons.py", line 155, in newfunc
    self._setup_plots()
  File "/home/runner/work/yt/yt/yt/visualization/profile_plotter.py", line 1099, in _setup_plots
    colorbar_handler=cbh,
  File "/home/runner/work/yt/yt/yt/visualization/profile_plotter.py", line 1537, in __init__
    self._init_image(x_data, y_data, data, x_scale, y_scale)
  File "/home/runner/work/yt/yt/yt/visualization/profile_plotter.py", line 1550, in _init_image
    norm = self.norm_handler.get_norm(image_data)
  File "/home/runner/work/yt/yt/yt/visualization/_handlers.py", line 219, in get_norm
    kw.setdefault("vmin", self.to_float(np.nanmin(data[np.isfinite(data)])))
  File "<__array_function__ internals>", line 6, in nanmin
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/numpy/lib/nanfunctions.py", line 326, in nanmin
    res = np.amin(a, axis=axis, out=out, **kwargs)
  File "<__array_function__ internals>", line 6, in amin
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/numpy/core/fromnumeric.py", line 2880, in amin
    keepdims=keepdims, initial=initial, where=where)
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/numpy/core/fromnumeric.py", line 84, in _wrapreduction
    return reduction(axis=axis, out=out, **passkwargs)
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/numpy/core/_methods.py", line 44, in _amin
    return umr_minimum(a, axis, None, out, keepdims, initial, where)
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/unyt/array.py", line 1674, in __array_ufunc__
    out_arr = func(np.asarray(inp), out=out_func, **kwargs)
ValueError: zero-size array to reduction operation minimum which has no identity
```
maybe it's gonna make other errors go away too.

**Comment by neutrinoceros** [comment]
Thank you ! I did not realise that the situation was an unfortunate result of a bug in my PR _and_ a bug in the upload_failed_answers.py script. I was wrongly suspecting a server side problem, but indeed I'm now almost certain that it's not, and probably no other PRs are affected save for #3849. Let's just close this.
