### ISSUE TITLE
DOC: errors in plot filters documentation

### ISSUE THREAD

**Issue by neutrinoceros** [yt-project/yt#3966]
### Bug report

**Bug summary**

Lately, we've been getting some ImportErrors in the docs build:
```
Traceback (most recent call last):
  File "temp.py", line 7, in <module>
    p.save()
  File "/var/jenkins_home/workspace/yt_docs_new/yt/visualization/_commons.py", line 140, in newfunc
    self._recreate_frb()
  File "/var/jenkins_home/workspace/yt_docs_new/yt/visualization/plot_window.py", line 380, in _recreate_frb
    self._frb[key]
  File "/var/jenkins_home/workspace/yt_docs_new/yt/visualization/fixed_resolution.py", line 170, in __getitem__
    buff = filter_registry[name](*args, **kwargs).apply(buff)
  File "/var/jenkins_home/workspace/yt_docs_new/yt/visualization/fixed_resolution_filters.py", line 70, in apply
    spl = _scipy.signal.convolve(buff, g2d)
  File "/var/jenkins_home/workspace/yt_docs_new/yt/utilities/on_demand_imports.py", line 21, in __getattr__
    raise self.error
ImportError: This functionality requires the scipy package to be installed.
Traceback (most recent call last):
  File "temp.py", line 13, in <module>
    plt.imshow(frb["gas", "density"].d)
  File "/var/jenkins_home/workspace/yt_docs_new/yt/visualization/fixed_resolution.py", line 170, in __getitem__
    buff = filter_registry[name](*args, **kwargs).apply(buff)
  File "/var/jenkins_home/workspace/yt_docs_new/yt/visualization/fixed_resolution_filters.py", line 70, in apply
    spl = _scipy.signal.convolve(buff, g2d)
  File "/var/jenkins_home/workspace/yt_docs_new/yt/utilities/on_demand_imports.py", line 21, in __getattr__
    raise self.error
ImportError: This functionality requires the scipy package to be installed.
```
I made an attempt at fixing this by requiring SciPy in docs env, but it didn't change anything. I also cannot reproduce this problem locally.
It could be a consequence of #3935

**Comment by neutrinoceros** [comment]
Reported what looks like the root cause upstream https://github.com/scipy/scipy/issues/16602

**Comment by neutrinoceros** [comment]
Discussion upstream helped me clarify that the root cause is an actual and *intentional* backward compatibility break:
On the jenkins server where we build docs, we have `glibc` 2.2.5 installed, but `scipy>=1.7` wheels are built within the `manylinux2014` image, which is *defined* as needing `glibc` 2.17 or newer (see [PEP 600](https://peps.python.org/pep-0600/)).
So, I see 3 possible approaches to resolve this, by decreasing order of difficulty
1) migrate docs builds to GHA
2) upgrade glibc on the test server, or the switch to a more recent Linux image ? (both sound out of my reach, and painful)
3) pin scipy < 1.7 for docs builds

Long term, I assume option 1 could be the only viable one, but it's by far the hardest to implement, and even if I started now, it's unrealistic to hope for completion before the new release. I have no clue how feasible option 2 is (I guess @Xarthisius should weigh in here). So I'll go with option 3 for now, and keep a link to the issue so it's easier to track down in the future.

**Comment by neutrinoceros** [comment]
Another option would be to build scipy from source, which feels feasible, but again, out of my reach.
