### ISSUE TITLE
Cannot project sz_kinetic field from Arepo dataset

### ISSUE THREAD

**Issue by jzuhone** [yt-project/yt#3975]
### Bug report

**Bug summary**

Following PR #2416, I'm getting a strange failure when trying to perform a projection of the built-in `"sz_kinetic"` field: 

**Code for reproduction**

```python
import yt
ds = yt.load("TNGHalo/halo_59.hdf5") # this is a dataset on yt-project.org/data
prj = yt.ProjectionPlot(ds, "z", [("gas","sz_kinetic")])
prj.save()
```

**Actual outcome**

```
yt : [INFO     ] 2022-06-14 12:36:16,137 Calculating time from 1.000e+00 to be 4.356e+17 seconds
yt : [INFO     ] 2022-06-14 12:36:16,254 Parameters: current_time              = 4.355810528213311e+17 s
yt : [INFO     ] 2022-06-14 12:36:16,255 Parameters: domain_dimensions         = [1 1 1]
yt : [INFO     ] 2022-06-14 12:36:16,256 Parameters: domain_left_edge          = [0. 0. 0.]
yt : [INFO     ] 2022-06-14 12:36:16,256 Parameters: domain_right_edge         = [205000. 205000. 205000.]
yt : [INFO     ] 2022-06-14 12:36:16,257 Parameters: cosmological_simulation   = 1
yt : [INFO     ] 2022-06-14 12:36:16,257 Parameters: current_redshift          = 0.0
yt : [INFO     ] 2022-06-14 12:36:16,257 Parameters: omega_lambda              = 0.6911
yt : [INFO     ] 2022-06-14 12:36:16,257 Parameters: omega_matter              = 0.3089
yt : [INFO     ] 2022-06-14 12:36:16,257 Parameters: omega_radiation           = 0.0
yt : [INFO     ] 2022-06-14 12:36:16,257 Parameters: hubble_constant           = 0.6774
yt : [INFO     ] 2022-06-14 12:36:16,314 Allocating for 1.011e+07 particles
Initializing coarse index : 100%|███████████████| 22/22 [00:00<00:00, 27.58it/s]
yt : [INFO     ] 2022-06-14 12:36:17,136 Updating index_order2 from 2 to 4
Initializing refined index: 100%|███████████████| 22/22 [00:03<00:00,  5.98it/s]
yt : [INFO     ] 2022-06-14 12:36:24,537 xlim = 0.000000 205000.000000
yt : [INFO     ] 2022-06-14 12:36:24,537 ylim = 0.000000 205000.000000
yt : [INFO     ] 2022-06-14 12:36:24,538 xlim = 0.000000 205000.000000
yt : [INFO     ] 2022-06-14 12:36:24,538 ylim = 0.000000 205000.000000
yt : [INFO     ] 2022-06-14 12:36:24,550 Making a fixed resolution buffer of (('gas', 'sz_kinetic')) 800 by 800
Traceback (most recent call last):
  File "/Users/jzuhone/proj_szk.py", line 3, in <module>
    prj = yt.ProjectionPlot(ds, "z", [("gas","sz_kinetic")])
  File "/Users/jzuhone/Source/yt/yt/visualization/plot_window.py", line 2315, in __init__
    PWViewerMPL.__init__(
  File "/Users/jzuhone/Source/yt/yt/visualization/plot_window.py", line 923, in __init__
    PlotWindow.__init__(self, *args, **kwargs)
  File "/Users/jzuhone/Source/yt/yt/visualization/plot_window.py", line 274, in __init__
    self._setup_plots()
  File "/Users/jzuhone/Source/yt/yt/visualization/plot_window.py", line 1121, in _setup_plots
    image = self.frb[f]
  File "/Users/jzuhone/Source/yt/yt/visualization/fixed_resolution.py", line 160, in __getitem__
    buff = self.ds.coordinates.pixelize(
  File "/Users/jzuhone/Source/yt/yt/geometry/coordinates/cartesian_coordinates.py", line 222, in pixelize
    return self._ortho_pixelize(
  File "/Users/jzuhone/Source/yt/yt/geometry/coordinates/cartesian_coordinates.py", line 378, in _ortho_pixelize
    chunk[field].in_units(ounits),
  File "/Users/jzuhone/Source/yt/yt/data_objects/data_containers.py", line 262, in __getitem__
    self.get_data(f)
  File "/Users/jzuhone/Source/yt/yt/data_objects/selection_objects/data_selection_objects.py", line 212, in get_data
    self._generate_fields(fields_to_generate)
  File "/Users/jzuhone/Source/yt/yt/data_objects/selection_objects/data_selection_objects.py", line 233, in _generate_fields
    fd = self._generate_field(field)
  File "/Users/jzuhone/Source/yt/yt/data_objects/data_containers.py", line 303, in _generate_field
    tr = self._generate_fluid_field(field)
  File "/Users/jzuhone/Source/yt/yt/data_objects/data_containers.py", line 322, in _generate_fluid_field
    rv = finfo(gen_obj)
  File "/Users/jzuhone/Source/yt/yt/fields/derived_field.py", line 285, in __call__
    dd = self._function(self, data)
  File "/Users/jzuhone/Source/yt/yt/fields/species_fields.py", line 55, in _density
    return data[ftype, f"{species}_fraction"] * data[ftype, "density"]
  File "/Users/jzuhone/opt/miniconda3/envs/py310/lib/python3.10/site-packages/unyt/array.py", line 1778, in __array_ufunc__
    out_arr = func(
ValueError: operands could not be broadcast together with shapes (0,3) (0,)
```

**Expected outcome**

Something weird seems to be happening when there are no particles in a chunk. 

**Version Information**

  * Operating System: macOS 
  * Python Version: 3.10.4
  * yt version: 4.1.dev0 (9389bb18f234bd19c3ad032d6fcd3ab85ca420cb)

**Comment by jzuhone** [comment]
@matthewturk I'm happy to dig into this, but any ideas as to how this happened based on your knowledge of PR #2416? I tried `git bisect` and it got me nowhere

**Comment by neutrinoceros** [comment]
Yeah I confirm that bisecting into #2416's history doesn't give out much info (most commits break this test but not for necessarily with the same error). It's definitely from this PR though.

**Comment by matthewturk** [comment]
So I think this is one of the things that happens if we're creating a vector field that shouldn't be one, or not creating one that should be.  In practice, it should not really ever be a problem because our shape is `(0,3)` and `(0,)` which means no entries, but it does because it still tries to apply the broadcasting rules.

It seems that there is some way that we are returning size 0 arrays, such that `return data[ftype, f"{species}_fraction"] * data[ftype, "density"]` fails.  And that's not the specific place we want it to fail, or to bail out, either.

What I think is happening is that we're iterating over chunks where one of the chunks is actually of zero size.  This may be because the number of particles included is 0, or it might be because the number of particles of the specific *type* are zero.

I *think* we should be able, in the loop on line 369 of `cartesian_coordinates.py`, to do a check if the field size is zero.  If it is, we should `continue`.  That would fix it in this case, but in principle I think we should also consider *instead* putting the fields we will request into the call to `.chunks()` in the list argument, and the `chunks` call should filter out the chunks with nothing to return.

**Comment by jzuhone** [comment]
@matthewturk so I did some more digging and what happens here is that the chunk does indeed have 0 size, but we try to get the fields here anyway (on line 99): 

https://github.com/yt-project/yt/blob/251b417031064c4c03e7f5b2d1e64cde420ef438/yt/data_objects/selection_objects/data_selection_objects.py#L84-L101

thus the particle position array has `shape` `(0,)`, and then we try to index it with two dimensions in line 247 of `particle_fields.py`, which assumes that it has a non-zero shape. 

Should we try to handle this in `cartesian_coordinates.py` as you suggested, or is there a smarter fix to be made in the `chunks()` method?
