### ISSUE TITLE
BUG: PlotContainer.set_font is broken (color)

### ISSUE THREAD

**Issue by neutrinoceros** [yt-project/yt#4263]
### Bug report

**Bug summary**

Setting the text color in a PlotContainer object currently doesn't work

**Code for reproduction**

```python
import yt

ds = yt.load_sample("IsolatedGalaxy")
p = yt.SlicePlot(ds, "z", ("gas", "density"))
p.set_font({"color": "blue"})
```

**Actual outcome**

```python-traceback
Traceback (most recent call last):
  File "/Users/robcleme/dev/yt-project/yt/t.py", line 5, in <module>
    p.set_font({"color": "blue"})
  File "/Users/robcleme/dev/yt-project/yt/yt/visualization/_commons.py", line 121, in newfunc
    retv = f(self, *args, **kwargs)
  File "/Users/robcleme/dev/yt-project/yt/yt/visualization/_commons.py", line 147, in newfunc
    self._setup_plots()
  File "/Users/robcleme/dev/yt-project/yt/yt/visualization/plot_window.py", line 1219, in _setup_plots
    self._set_font_properties()
  File "/Users/robcleme/dev/yt-project/yt/yt/visualization/plot_container.py", line 387, in _set_font_properties
    self.plots[f]._set_font_properties(self._font_properties, self._font_color)
  File "/Users/robcleme/dev/yt-project/yt/yt/visualization/base_plot_types.py", line 201, in _set_font_properties
    label.set_color(self.font_color)
AttributeError: 'WindowPlotMPL' object has no attribute 'font_color'
```

**Comment by neutrinoceros** [comment]
This bug is present as far back as yt 4.0.0. I have not checked older versions.
