### ISSUE TITLE
Projection on some axis fail in curvilinear geometries

### ISSUE THREAD

**Issue by Xarthisius** [yt-project/yt#4304]
### Bug report

**Bug summary**

Certain type of projections ("y" in cylindrical and "z" in polar) fail in curvilinear geometries

**Code for reproduction**

```python
import yt
ds = yt.load("amrvac/bw_cylindrical_3D0000.dat")
proj = ds.proj("density", 1)
frb = proj.to_frb((1.0, "unitary"), 256)
frb.render("density")
```

**Actual outcome**

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "yt/visualization/fixed_resolution.py", line 201, in render
    return self[item]
  File "yt/visualization/fixed_resolution.py", line 574, in __getitem__
    pixelize_cylinder(
  File "yt/utilities/lib/pixelization_routines.pyx", line 522, in yt.utilities.lib.pixelization_routines.pixelize_cylinder
ValueError: Buffer has wrong number of dimensions (expected 2, got 1)
```

**Expected outcome**

No error

**Version Information**
  * Operating System: Ubuntu 20.04
  * Python Version: 3.8.13
  * yt version: https://github.com/yt-project/yt/commit/97307f4ebc78294717b718b77ecab2c1516d601a

**Comment by neutrinoceros** [comment]
I intend to take a look at this tomorrow, I'm hopeful I can fix it for yt 4.1.4

**Comment by neutrinoceros** [comment]
Here's a slightly modified version of the script that is compatible with yt 4.0.0 (as well as 4.2dev0)
```python
import yt

ds = yt.load_sample("bw_cylindrical_3d")
proj = ds.proj("density", 1)
frb = proj.to_frb((1.0, "unitary"), 256)
frb["density"]
```

I checked that the bug was already present in yt 4.0.0, so if it's a regression it's an old one. I won't attempt to bisect this further, I'll just dive in and see where it fails.

**Comment by neutrinoceros** [comment]
It seems very likely that this bug is coming from an incomplete special casing done on https://github.com/yt-project/yt/blob/4eda8b275e0e979f982b32bb700736315caf9f43/yt/data_objects/selection_objects/data_selection_objects.py#L593-L595

I'll work it out
