### ISSUE TITLE
FileNotFoundError when using PyneMoabHex8Dataset in SlicePlot

### ISSUE THREAD

**Issue by ahnaf-tahmid-chowdhury** [yt-project/yt#4535]
### Bug report

**Bug summary**

When using the PyneMoabHex8Dataset from the yt.frontends.moab.api module, a FileNotFoundError is raised, indicating that the specified file pyne_mesh_139757250631632 cannot be found.

**Code for reproduction**

```python
import numpy as np
from pyne import mesh, material 
from pyne.xs.channels import sigma_t

# import a few things necessary for plotting in the notebook
from yt.config import ytcfg; ytcfg["yt","suppressStreamLogging"] = "True"
from yt.frontends.moab.api import PyneMoabHex8Dataset
from yt.mods import SlicePlot

# create reactor mesh
m = mesh.Mesh(structured_coords=[np.linspace(0.0, 1.0, 101), np.linspace(0.0, 1.0, 101), [0.0, 1.0]], structured=True)
fuel = material.from_atom_frac({'U235': 0.045, 'U238': 0.955, 'O16': 2.0}, mass=1.0, density=10.7)
cool = material.from_atom_frac({'H1': 2.0, 'O16': 1.0}, mass=1.0, density=1.0)
for i, mat, ve in m:
    coord = m.mesh.get_coords(ve)
    m.mats[i] = fuel if (coord[0]**2 + coord[1]**2) <= 0.5**2 else cool

# create a total cross section tag on the mesh
m.sigma_t = mesh.ComputedTag(lambda mesh, i: sigma_t(mesh.mats[i], group_struct=[10.0, 1e-6], phi_g=[1.0])[0])

# create a uranium mass tag on the mesh
m.u_mass = mesh.ComputedTag(lambda mesh, i: max(mesh.mats[i]['U':'Np'].mass, 0.0))

# plot the total cross section
SlicePlot(PyneMoabHex8Dataset(m), 'z', 'sigma_t', origin='native').display()
```

**Actual outcome**

```console
FileNotFoundError                         Traceback (most recent call last)
Cell In[27], line 4
      2 from yt import SlicePlot
      3 # plot the total cross section
----> 4 SlicePlot(PyneMoabHex8Dataset(m), 'z', 'sigma_t', origin='native').display()

File [/opt/nuclear-boy/lib/python3.11/site-packages/yt/data_objects/static_output.py:220](https://file+.vscode-resource.vscode-cdn.net/opt/nuclear-boy/lib/python3.11/site-packages/yt/data_objects/static_output.py:220), in Dataset.__new__(cls, filename, *args, **kwargs)
    216     is_stream = hasattr(filename, "get_fields") and hasattr(
    217         filename, "get_particle_type"
    218     )
    219     if not is_stream:
--> 220         obj.__init__(filename, *args, **kwargs)
    221     return obj
    222 apath = os.path.abspath(os.path.expanduser(filename))

File [/opt/nuclear-boy/lib/python3.11/site-packages/yt/frontends/moab/data_structures.py:162](https://file+.vscode-resource.vscode-cdn.net/opt/nuclear-boy/lib/python3.11/site-packages/yt/frontends/moab/data_structures.py:162), in PyneMoabHex8Dataset.__init__(self, pyne_mesh, dataset_type, storage_filename, units_override, unit_system)
    160 filename = f"pyne_mesh_{id(pyne_mesh)}"
    161 self.pyne_mesh = pyne_mesh
--> 162 Dataset.__init__(
    163     self,
    164     str(filename),
    165     dataset_type,
    166     units_override=units_override,
    167     unit_system=unit_system,
...
--> 363     retv = int(os.stat(self.parameter_filename)[ST_CTIME])
    364     name_as_bytes = bytearray(map(ord, self.parameter_filename))
    365     retv += fnv_hash(name_as_bytes)

FileNotFoundError: [Errno 2] No such file or directory: '/mnt/Data/Projects/PyNE/tutorial/pyne_mesh_139757250631632'
```

**Expected outcome**

I expect the code to plot the total cross section using the PyneMoabHex8Dataset successfully, without raising a FileNotFoundError. The plot should be displayed without any issues.

**Version Information**

  * Operating System: Ubuntu 23.04
  * Python Version: 3.11.2
  * yt version: 4.2.1
  * Other Libraries (if applicable): PyNE

**Comment by neutrinoceros** [comment]
Thanks a lot for reporting !
This sounds an awful lot similar to #4532, I bet this comes from the same kind of problem. If so, it should also be easy to fix.

btw, there's simpler way to deactivate yt's logging, instead of
```python
from yt.config import ytcfg; ytcfg["yt","suppressStreamLogging"] = "True"
```

you can do this
```python
import yt
yt.set_logging_level("critical")
```

**Comment by ahnaf-tahmid-chowdhury** [comment]
I am using the pip version. However, I have changed the following code in `yt/frontends/fits/data_structures.py` #4533 

```python
    @property
    def filename(self) -> str:
        if self._input_filename.startswith("InMemory"):
            return self._input_filename
        else:
            return super().filename

    @cached_property
    def unique_identifier(self) -> str:
        if self.filename.startswith("InMemory"):
            return str(time.time())
        else:
            return super().unique_identifier
```
But I am still facing the same problem.

**Comment by neutrinoceros** [comment]
What happens if you replace `"InMemory"` with `"pyne_mesh"` ?
(meanwhile, I'm trying to install `pyne` to reproduce the problem)

**Comment by ahnaf-tahmid-chowdhury** [comment]
Nothing happened. It seems the Dataset needs to create a file name `pyne_mesh_{id(pyne_mesh)}` which is getting ignored.

**Comment by neutrinoceros** [comment]
Can you try this patch instead ?
```patch
diff --git a/yt/frontends/moab/data_structures.py b/yt/frontends/moab/data_structures.py
index 2c01615ac..94ac9dcb4 100644
--- a/yt/frontends/moab/data_structures.py
+++ b/yt/frontends/moab/data_structures.py
@@ -168,6 +168,10 @@ class PyneMoabHex8Dataset(Dataset):
         )
         self.storage_filename = storage_filename
 
+    @property
+    def filename(self) -> str:
+        return self._input_filename
+
     def _set_code_unit_attributes(self):
         # Almost everything is regarded as dimensionless in MOAB, so these will
         # not be used very much or at all.
```

if it fails, please include the complete error message.

Unfortunately I am currently unable to try this myself because I cannot install pyne from source and apparently don't have access to conda.

**Comment by ahnaf-tahmid-chowdhury** [comment]
This time a new error:

```console
NameError                                 Traceback (most recent call last)
Cell In[3], line 1
----> 1 from yt.frontends.moab.api import PyneMoabHex8Dataset
      2 from yt import SlicePlot
      3 # plot the total cross section

File [/opt/nuclear-boy/lib/python3.11/site-packages/yt/__init__.py:74](https://file+.vscode-resource.vscode-cdn.net/opt/nuclear-boy/lib/python3.11/site-packages/yt/__init__.py:74)
     71 from yt.units.unit_object import define_unit  # type: ignore
     72 from yt.utilities.logger import set_log_level, ytLogger as mylog
---> 74 frontends = _frontend_container()
     76 import yt.visualization.volume_rendering.api as volume_rendering
     77 from yt.frontends.stream.api import hexahedral_connectivity

File [/opt/nuclear-boy/lib/python3.11/site-packages/yt/frontends/api.py:54](https://file+.vscode-resource.vscode-cdn.net/opt/nuclear-boy/lib/python3.11/site-packages/yt/frontends/api.py:54), in _frontend_container.__init__(self)
     52 for frontend in _frontends:
     53     _mod = f"yt.frontends.{frontend}.api"
---> 54     setattr(self, frontend, importlib.import_module(_mod))
     55 setattr(self, "api", importlib.import_module("yt.frontends.api"))
     56 setattr(self, "__name__", "yt.frontends.api")

File [/usr/lib/python3.11/importlib/__init__.py:126](https://file+.vscode-resource.vscode-cdn.net/usr/lib/python3.11/importlib/__init__.py:126), in import_module(name, package)
    124             break
    125         level += 1
--> 126 return _bootstrap._gcd_import(name[level:], package, level)
...
    179 def _set_code_unit_attributes(self):
    180     # Almost everything is regarded as dimensionless in MOAB, so these will
    181     # not be used very much or at all.

NameError: name 'cached_property' is not defined
```
It seems, there is a missing import statement

**Comment by neutrinoceros** [comment]
Yes, this should be `from functools import cached_property`

**Comment by yut23** [comment]
That fixed the `FileNotFoundError`, but then I got this error:
```
Traceback (most recent call last):
  File "/home/eric/build/yt/test.py", line 25, in <module>
    SlicePlot(PyneMoabHex8Dataset(m), 'z', 'sigma_t', origin='native').display()
  File "/home/eric/build/yt/yt/visualization/plot_window.py", line 1816, in __init__
    (bounds, center, display_center) = get_window_parameters(
  File "/home/eric/build/yt/yt/visualization/plot_window.py", line 70, in get_window_parameters
    width = ds.coordinates.sanitize_width(axis, width, None)
  File "/home/eric/build/yt/yt/geometry/coordinates/coordinate_handler.py", line 259, in sanitize_width
    self.ds.index
  File "/home/eric/build/yt/yt/data_objects/static_output.py", line 610, in index
    self._instantiated_index = self._index_class(
  File "/home/eric/build/yt/yt/frontends/moab/data_structures.py", line 119, in __init__
    super().__init__(ds, dataset_type)
  File "/home/eric/build/yt/yt/geometry/unstructured_mesh_handler.py", line 22, in __init__
    super().__init__(ds, dataset_type)
  File "/home/eric/build/yt/yt/geometry/geometry_handler.py", line 39, in __init__
    self._setup_geometry()
  File "/home/eric/build/yt/yt/geometry/unstructured_mesh_handler.py", line 26, in _setup_geometry
    self._initialize_mesh()
  File "/home/eric/build/yt/yt/frontends/moab/data_structures.py", line 136, in _initialize_mesh
    vind = vind.reshape(len(vind) // 8, 8)
ValueError: cannot reshape array of size 80000 into shape (1250,8)
```
`vind` has shape `(10000, 8)`, and commenting out the offending `reshape` seems to work.

**Comment by ahnaf-tahmid-chowdhury** [comment]
```console
ValueError                                Traceback (most recent call last)
Cell In[3], line 4
      2 from yt import SlicePlot
      3 # plot the total cross section
----> 4 SlicePlot(PyneMoabHex8Dataset(m), 'z', 'sigma_t', origin='native').display()

File [/opt/nuclear-boy/lib/python3.11/site-packages/yt/visualization/plot_window.py:1814](https://file+.vscode-resource.vscode-cdn.net/opt/nuclear-boy/lib/python3.11/site-packages/yt/visualization/plot_window.py:1814), in AxisAlignedSlicePlot.__init__(self, ds, normal, fields, center, width, axes_unit, origin, fontsize, field_parameters, window_size, aspect, data_source, buff_size, north_vector)
   1812 # this will handle time series data and controllers
   1813 axis = fix_axis(normal, ds)
-> 1814 (bounds, center, display_center) = get_window_parameters(
   1815     axis, center, width, ds
   1816 )
   1817 if field_parameters is None:
   1818     field_parameters = {}

File [/opt/nuclear-boy/lib/python3.11/site-packages/yt/visualization/plot_window.py:70](https://file+.vscode-resource.vscode-cdn.net/opt/nuclear-boy/lib/python3.11/site-packages/yt/visualization/plot_window.py:70), in get_window_parameters(axis, center, width, ds)
     69 def get_window_parameters(axis, center, width, ds):
---> 70     width = ds.coordinates.sanitize_width(axis, width, None)
     71     center, display_center = ds.coordinates.sanitize_center(center, axis)
     72     xax = ds.coordinates.x_axis[axis]

File [/opt/nuclear-boy/lib/python3.11/site-packages/yt/geometry/coordinates/coordinate_handler.py:259](https://file+.vscode-resource.vscode-cdn.net/opt/nuclear-boy/lib/python3.11/site-packages/yt/geometry/coordinates/coordinate_handler.py:259), in CoordinateHandler.sanitize_width(self, axis, width, depth)
    256 def sanitize_width(self, axis, width, depth):
    257     if width is None:
...
    133 vind = np.asarray(vind, dtype=np.int64)
--> 134 vind = vind.reshape(len(vind) [/](https://file+.vscode-resource.vscode-cdn.net/)[/](https://file+.vscode-resource.vscode-cdn.net/) 8, 8)
    135 self.meshes = [PyneHex8Mesh(0, self.index_filename, vind, coords, self)]

ValueError: cannot reshape array of size 80000 into shape (1250,8)
```

**Comment by neutrinoceros** [comment]
Try this
```patch
diff --git a/yt/frontends/moab/data_structures.py b/yt/frontends/moab/data_structures.py
index 2c01615ac..f7626942e 100644
--- a/yt/frontends/moab/data_structures.py
+++ b/yt/frontends/moab/data_structures.py
@@ -132,7 +132,9 @@ class PyneMeshHex8Hierarchy(UnstructuredIndex):
                 )
             )
         vind = np.asarray(vind, dtype=np.int64)
-        vind = vind.reshape(len(vind) // 8, 8)
+        if vind.ndim == 1:
+            vind = vind.reshape(len(vind) // 8, 8)
+        assert vind.ndim == 2 and vind.shape[1] == 8
         self.meshes = [PyneHex8Mesh(0, self.index_filename, vind, coords, self)]
 
     def _detect_output_fields(self):
```

**Comment by ahnaf-tahmid-chowdhury** [comment]
Firstly, I have got this

```console
AttributeError                            Traceback (most recent call last)
Cell In[3], line 4
      2 from yt import SlicePlot
      3 # plot the total cross section
----> 4 SlicePlot(PyneMoabHex8Dataset(m), 'z', 'sigma_t', origin='native').display()

File /opt/nuclear-boy/lib/python3.11/site-packages/yt/visualization/plot_window.py:1833, in AxisAlignedSlicePlot.__init__(self, ds, normal, fields, center, width, axes_unit, origin, fontsize, field_parameters, window_size, aspect, data_source, buff_size, north_vector)
   1825 else:
   1826     slc = ds.slice(
   1827         axis,
   1828         center[axis],
   (...)
   1831         data_source=data_source,
   1832     )
-> 1833     slc.get_data(fields)
   1834 validate_mesh_fields(slc, fields)
   1835 PWViewerMPL.__init__(
   1836     self,
   1837     slc,
   (...)
   1845     geometry=ds.geometry,
   1846 )

File /opt/nuclear-boy/lib/python3.11/site-packages/yt/data_objects/selection_objects/data_selection_objects.py:205, in YTSelectionContainer.get_data(self, fields)
...

AttributeError: module 'numpy' has no attribute 'bool'.
`np.bool` was a deprecated alias for the builtin `bool`. To avoid this error in existing code, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
```

Then I replaced `np.bool` with `bool` and got this

```console
TypeError                                 Traceback (most recent call last)
Cell In[5], line 4
      2 from yt import SlicePlot
      3 # plot the total cross section
----> 4 SlicePlot(PyneMoabHex8Dataset(m), 'z', 'sigma_t', origin='native').display()

File [/opt/nuclear-boy/lib/python3.11/site-packages/yt/visualization/plot_window.py:1833](https://file+.vscode-resource.vscode-cdn.net/opt/nuclear-boy/lib/python3.11/site-packages/yt/visualization/plot_window.py:1833), in AxisAlignedSlicePlot.__init__(self, ds, normal, fields, center, width, axes_unit, origin, fontsize, field_parameters, window_size, aspect, data_source, buff_size, north_vector)
   1825 else:
   1826     slc = ds.slice(
   1827         axis,
   1828         center[axis],
   (...)
   1831         data_source=data_source,
   1832     )
-> 1833     slc.get_data(fields)
   1834 validate_mesh_fields(slc, fields)
   1835 PWViewerMPL.__init__(
   1836     self,
   1837     slc,
   (...)
   1845     geometry=ds.geometry,
   1846 )

File [/opt/nuclear-boy/lib/python3.11/site-packages/yt/data_objects/selection_objects/data_selection_objects.py:205](https://file+.vscode-resource.vscode-cdn.net/opt/nuclear-boy/lib/python3.11/site-packages/yt/data_objects/selection_objects/data_selection_objects.py:205), in YTSelectionContainer.get_data(self, fields)
...
---> 14 m.sigma_t = mesh.ComputedTag(lambda mesh, i: sigma_t(mesh.mats[i], group_struct=[10.0, 1e-6], phi_g=[1.0])[0])
     16 # create a uranium mass tag on the mesh
     17 m.u_mass = mesh.ComputedTag(lambda mesh, i: max(mesh.mats[i]['U':'Np'].mass, 0.0))

TypeError: 'list' object is not callable
```
It seems It the `sigma_t` function is returning a list, and `get_data` is trying to call it as a function to compute the value for the `m.sigma_t` tag.

**Comment by neutrinoceros** [comment]
The first error is very surprising to me: I don't see `np.bool` used anywhere in the code base, and your traceback seems to be truncated so I can't see the line where it appears. Any chance you could show the exact line and where it is ?

The second error is also truncated, and it looks like the last line that's included doesn't live in yt but in PyNE (in which case, we might need to get PyNE people involved to fix this)

**Comment by neutrinoceros** [comment]
I think I found where the remaining `np.bool` instances were: in PyNE. I've opened [a PR there to fix it](https://github.com/pyne/pyne/pull/1485). In the mean time, I recommend downgrading to numpy<1.24 rather than manually patching your installed PyNE copy.

**Comment by ahnaf-tahmid-chowdhury** [comment]
I am currently updating the PyNE docs where I have found the issue. The first error code can be accessed through [pyne.mesh](https://github.com/pyne/pyne/blob/9918b97c83c5da4972ab1b5447150592ced8d513/pyne/mesh.py#L158)

The last line of the second error is showing how the `sigma_t` tag was made in the code.  `sigma_t` is created using the `mesh.ComputedTag` constructor. It calculates the total cross section for each mesh element based on the material assigned to it.

**Comment by neutrinoceros** [comment]
As far as I can tell #4536 fixes everything we've identified as broken so far on the yt side.
Beyond that, I recommend moving the discussion to PyNE. That said, we can keep this open until we're confident that there are no other problems on this side :)

**Comment by ahnaf-tahmid-chowdhury** [comment]
It seems it is working now. I have made some changes in my code which was causing problem.

```python
sigma_t = list(m.sigma_t)
u_mass = list(m.u_mass)
```

Thank you for the support. I believe I can close this issue now.
