### ISSUE TITLE
BUG: `yt.plot_2d` fails on 2D RAMSES data

### ISSUE THREAD

**Issue by neutrinoceros** [yt-project/yt#4628]
### Bug report

**Bug summary**

It's easy enough to understand why: we're not even attempting to parse dimensionality and go straight to assuming 3D
https://github.com/yt-project/yt/blob/43d32a64147b184f043a37ce8c9e82131293b777/yt/frontends/ramses/data_structures.py#L886

**Code for reproduction**

```python
import yt
ds = yt.load("~/Downloads/output_00001/info_00001.txt")

def test_plot2d():
    p = yt.plot_2d(ds, ("gas", "density"))

def test_sliceplot():
    p = yt.SlicePlot(ds, "z", ("gas", "density"))
```

**Actual outcome**

first test:
```
...
        if ds.dimensionality != 2:
>           raise RuntimeError("plot_2d only plots 2D datasets!")
E           RuntimeError: plot_2d only plots 2D datasets!
```
second test
```
...
yt/frontends/ramses/io_utils.pyx:73: in yt.frontends.ramses.io_utils.read_amr
    pos[:ng, 2] = f.read_vector("d") - nz
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

>   raise ValueError('Size obtained (%s) does not match with the expected '
E   ValueError: Size obtained (4) does not match with the expected size (8) of multi-item record
```
**Expected outcome**
beautiful plots

**Version Information**
  * Operating System: MacOS
  * Python Version: 3.11.4
  * yt version: 4.3.0dev0 (but most likely any version)
  * Other Libraries (if applicable):

yt installed from source

**Comment by neutrinoceros** [comment]
I think I got the fix for the Python side of things (parsing dimensionality)
```patch
diff --git a/yt/frontends/ramses/data_structures.py b/yt/frontends/ramses/data_structures.py
index 59acf6903..781eaa963 100644
--- a/yt/frontends/ramses/data_structures.py
+++ b/yt/frontends/ramses/data_structures.py
@@ -883,7 +883,6 @@ class RAMSESDataset(Dataset):
         # These should be explicitly obtained from the file, but for now that
         # will wait until a reorganization of the source tree and better
         # generalization.
-        self.dimensionality = 3
         self.refine_by = 2
         self.parameters["HydroMethod"] = "ramses"
         self.parameters["Time"] = 1.0  # default unit is 1...
@@ -943,8 +942,12 @@ class RAMSESDataset(Dataset):
                 % rheader["ordering type"]
             )
         self.parameters.update(rheader)
+        self.dimensionality = self.parameters["ndim"]
+
         self.domain_left_edge = np.zeros(3, dtype="float64")
-        self.domain_dimensions = np.ones(3, dtype="int32") * 2 ** (self.min_level + 1)
+        self.domain_dimensions = np.ones(3, dtype="int32")
+        self.domain_dimensions[: self.dimensionality] = 2 ** (self.min_level + 1)
+
         self.domain_right_edge = np.ones(3, dtype="float64")
         # This is likely not true, but it's not clear
         # how to determine the boundary conditions
```

Now both tests fail with the same error. Here's the full traceback
```python-traceback
Traceback (most recent call last):
  File "/Users/robcleme/dev/yt-project/yt/t.py", line 3, in <module>
    p = yt.SlicePlot(ds, "z", ("gas", "density"))
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/robcleme/dev/yt-project/yt/yt/visualization/plot_window.py", line 1816, in __init__
    (bounds, center, display_center) = get_window_parameters(
                                       ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/robcleme/dev/yt-project/yt/yt/visualization/plot_window.py", line 70, in get_window_parameters
    width = ds.coordinates.sanitize_width(axis, width, None)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/robcleme/dev/yt-project/yt/yt/geometry/coordinates/coordinate_handler.py", line 259, in sanitize_width
    self.ds.index
  File "/Users/robcleme/dev/yt-project/yt/yt/data_objects/static_output.py", line 610, in index
    self._instantiated_index = self._index_class(
                               ^^^^^^^^^^^^^^^^^^
  File "/Users/robcleme/dev/yt-project/yt/yt/frontends/ramses/data_structures.py", line 545, in __init__
    super().__init__(ds, dataset_type)
  File "/Users/robcleme/dev/yt-project/yt/yt/geometry/geometry_handler.py", line 39, in __init__
    self._setup_geometry()
  File "/Users/robcleme/dev/yt-project/yt/yt/geometry/oct_geometry_handler.py", line 15, in _setup_geometry
    self._initialize_oct_handler()
  File "/Users/robcleme/dev/yt-project/yt/yt/frontends/ramses/data_structures.py", line 553, in _initialize_oct_handler
    self.domains = [RAMSESDomainFile(self.dataset, i + 1) for i in cpu_list]
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/robcleme/dev/yt-project/yt/yt/frontends/ramses/data_structures.py", line 553, in <listcomp>
    self.domains = [RAMSESDomainFile(self.dataset, i + 1) for i in cpu_list]
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/robcleme/dev/yt-project/yt/yt/frontends/ramses/data_structures.py", line 223, in __init__
    self._read_amr()
  File "/Users/robcleme/dev/yt-project/yt/yt/frontends/ramses/data_structures.py", line 318, in _read_amr
    max_level = read_amr(
                ^^^^^^^^^
  File "yt/frontends/ramses/io_utils.pyx", line 73, in yt.frontends.ramses.io_utils.read_amr
    pos[:ng, 2] = f.read_vector("d") - nz
  File "yt/utilities/cython_fortran_utils.pyx", line 132, in yt.utilities.cython_fortran_utils.FortranFile.read_vector
    raise ValueError('Size obtained (%s) does not match with the expected '
ValueError: Size obtained (4) does not match with the expected size (8) of multi-item record
```

**Comment by chrishavlin** [comment]
Spent a little time looking at that `_read_amr` and it **seemed** easy enough to adjust for 2D, but then it ran into chunking/octree issues that I'm not sure what to do with...  

here's a diff of what I tried (on top of @neutrinoceros's diff, also note that I tried using just a 2D `pos` rather than adding a dummy dimension and it didn't make difference): 

```diff
diff --git a/yt/frontends/ramses/io_utils.pyx b/yt/frontends/ramses/io_utils.pyx
index 7becee634..2d05f591a 100644
--- a/yt/frontends/ramses/io_utils.pyx
+++ b/yt/frontends/ramses/io_utils.pyx
@@ -25,15 +25,19 @@ def read_amr(FortranFile f, dict headers,
 
     cdef INT64_t ncpu, nboundary, max_level, nlevelmax, ncpu_and_bound
     cdef DOUBLE_t nx, ny, nz
-    cdef INT64_t ilevel, icpu, n, ndim, skip_len
+    cdef INT64_t ilevel, icpu, n, ndim, skip_len, idim
     cdef INT32_t ng, buffer_size
     cdef np.ndarray[np.int32_t, ndim=2] numbl
     cdef np.ndarray[np.float64_t, ndim=2] pos
+    cdef np.ndarray[np.float64_t, ndim=1] nxyz
 
     ndim = headers['ndim']
     numbl = headers['numbl']
     nboundary = headers['nboundary']
+
     nx, ny, nz = (((i-1.0)/2.0) for i in headers['nx'])
+    nxyz = np.array([nx, ny, nz])
+
     nlevelmax = headers['nlevelmax']
     ncpu = headers['ncpu']
 
@@ -68,9 +72,12 @@ def read_amr(FortranFile f, dict headers,
                 pos = np.empty((ng, 3), dtype="d")
                 buffer_size = ng
 
-            pos[:ng, 0] = f.read_vector("d") - nx
-            pos[:ng, 1] = f.read_vector("d") - ny
-            pos[:ng, 2] = f.read_vector("d") - nz
+            for idim in range(ndim):
+                pos[:ng, idim] = f.read_vector("d") - nxyz[idim]
+
+            if ndim == 2:
+                # fill in the 3rd dummy dim??
+                pos[:ng, 2] = 0.5
 
             # Skip father, neighbor, son, cpu map and refinement map
             f.skip(skip_len)
```

which no longer errors. but data selection is still not working:  running the plot (**any** data selection) does not identify any chunks with data so you get errors like:

```python
ds.all_data()[('ramses', 'Density')]
```
```
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
Input In [2], in <cell line: 1>()
----> 1 ds.all_data()[('ramses', 'Density')]

File ~/src/yt_/yt_dev/yt/yt/data_objects/data_containers.py:235, in YTDataContainer.__getitem__(self, key)
    233         return self.field_data[f]
    234     else:
--> 235         self.get_data(f)
    236 # fi.units is the unit expression string. We depend on the registry
    237 # hanging off the dataset to define this unit object.
    238 # Note that this is less succinct so that we can account for the case
    239 # when there are, for example, no elements in the object.
    240 try:

File ~/src/yt_/yt_dev/yt/yt/data_objects/selection_objects/data_selection_objects.py:205, in YTSelectionContainer.get_data(self, fields)
    201         fluids.append(field_key)
    202 # The _read method will figure out which fields it needs to get from
    203 # disk, and return a dict of those fields along with the fields that
    204 # need to be generated.
--> 205 read_fluids, gen_fluids = self.index._read_fluid_fields(
    206     fluids, self, self._current_chunk
    207 )
    208 for f, v in read_fluids.items():
    209     self.field_data[f] = self.ds.arr(v, units=finfos[f].units)

File ~/src/yt_/yt_dev/yt/yt/geometry/geometry_handler.py:241, in Index._read_fluid_fields(self, fields, dobj, chunk)
    239 else:
    240     chunk_size = chunk.data_size
--> 241 fields_to_return = self.io._read_fluid_selection(
    242     self._chunk_io(dobj), selector, fields_to_read, chunk_size
    243 )
    244 return fields_to_return, fields_to_generate

File ~/src/yt_/yt_dev/yt/yt/frontends/ramses/io.py:215, in IOHandlerRAMSES._read_fluid_selection(self, chunks, selector, fields, size)
    213 d = {}
    214 for field in fields:
--> 215     d[field] = np.concatenate(tr.pop(field))
    217 return d

KeyError: ('ramses', 'Density')
```

That comes up because `RAMSESIndex._identify_base_chunk()` is not identifying any intersected domains. So not sure if my attempt at fixing `_read_amr` is the problem or some other location where there's a hardcoded 3rd dimension....
