### ISSUE TITLE
BUG: calling `yt.load_sample` with no arguments is broken on main

### ISSUE THREAD

**Issue by neutrinoceros** [yt-project/yt#4691]
### Bug report

**Bug summary**

This is a regression in yt 4.3 (dev)

I suspect it came from #4646 (cc @chrishavlin). It also shows that this path is currently not tested.

**Code for reproduction**

```shell
$ python -c "import yt; yt.load_sample()`
```

**Actual outcome**

```python-traceback
One can see which sample datasets are available at: https://yt-project.org/data
or alternatively by running: yt.sample_data.api.get_data_registry_table()
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/robcleme/dev/yt-project/yt/yt/loaders.py", line 1666, in load_sample
    loadable_path, load_kwargs = _get_sample_data(
    ^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: cannot unpack non-iterable NoneType object
```

**Expected outcome**
with yt 4.2.2, no error is raised
```
One can see which sample datasets are available at: https://yt-project.org/data
or alternatively by running: yt.sample_data.api.get_data_registry_table()
```

**Version Information**
  * Operating System: any
  * Python Version: any
  * yt version: 4.3.0dev0
  * Other Libraries (if applicable): N/A

**Comment by neutrinoceros** [comment]
Be my guest !
